### ISSUE TITLE
[BUG] AUX1 Label of input active (not updating)

### ISSUE THREAD

**Issue by WesleyvN** [bitfocus/companion-module-bmd-atem#101]
Hi, it's looking that i have find a bug at this module! For now what i can find is that the Actual Aux source is not up to date (to the actual state at the Mixer).

If i need to provide more info please do not hesitate to contact me!

Bug:
Variable from ATEM Aux bus is not updating($(ATEM Television Studio Pro HD:aux1_input))!

- Switch the source of the AUX1 bus to a different Input 
- The Variable is not updated at the Instance -> Config -> List Of Dynamic Variables
- When i Disable the instance and Enable it again the actual input is shown at the List Of Dynamic Variables.
     (after changing the input there is not a update of this variable)

**Beware i have don this by selecting the Model (TV Studio Pro HD)and also try it by using the Auto Detect function** 

Setup:
Companion on Raspberry Pi (Paspberry Pi 4 / 4GB ram) (pulled from GIT 23-12-2020)
1x Streamdeck XL
1x Streamdeck
Blackmagic ATEM Television Studio Pro HD 

Thanks in advance and good luck!

Wesley

**Comment by Julusian** [comment]
This is fixed in the `2.2.0-77ba794-2756` beta build
