### ISSUE TITLE
Instance unavailable when Companion starts, until pressing Apply

### ISSUE THREAD

**Issue by singletrackrecs** [bitfocus/companion-module-bmd-atem#104]
Hi, I don't know if this is the expected behaviour, but when my ATEM is not connected on the network, the ATEM instance is not accessible in Companion at all - it disappears from the presets section and the button menus completely.  Pre-existing buttons are marked as "(undefined)".

When I first add the ATEM instance it can be programmed without the hardware... but then it stops working.  I'm pretty sure that if I connect the hardware and then relaunch Companion that it all starts working again, but while the instance is in the 'Connecting' state it cannot be used. Any help appreciated as offline configuration is incredibly useful.  Thank you

**Comment by singletrackrecs** [comment]
Immediate update ----

Just figured out that if I go to the instance config and hit Apply Changes (not having changed anything) - it all starts working, hardware still disconnected, but I can continue with offline config.

**Comment by Julusian** [comment]
This is fixed in companion-2.2.0-d3464b0-2811
