### ISSUE TITLE
[BUG] Atem not connecting

### ISSUE THREAD

**Issue by antlear** [bitfocus/companion-module-bmd-atem#105]
**Describe the bug**
Was testing out the latest build yesterday with a Blackmagic Atem and it would fail to see the device. If I rolled back to the last general release it works fine and connects.

**Comment by Julusian** [comment]
Does it give any kind of error or log lines when this happens?
what os are you using?

**Comment by WardCameron** [comment]
I got a messsage today regarding the same issue. The new build: c81e24b-2796 fixed the connection problem for my ATEM

**Comment by dmbaird61** [comment]
I have downloaded the newest update to Companion and my ATEM Mini Pro won't connect....help!!!!

**Comment by WardCameron** [comment]
Download the fifth build on this page: https://bitfocus.io/companion/download/builds/. It specifically fixes that error...or at least it did for me. It is beta though.

**Comment by dmbaird61** [comment]
I tried the build ending in 2796 suggested above...that didn't change things.  I keep getting a "connecting" notice but no "ok" as I had before.  My programming all blew up.  I'll try your suggestion.  Is that the build ending in 2799?

**Comment by WardCameron** [comment]
Maybe try one of the newer betas. For me, the Atem build worked for the connection.  It didn't solve the problem of Companion showing dynamically displaying the names of images in the stills gallery.

**Comment by dmbaird61** [comment]
Thanks Ward.  One thing that helped was entering the IP address of the mini manually to the Companion site.  This, along with the version you suggested, fixed my issue.

**Comment by WardCameron** [comment]
Awesome. Sorry, I just assumed step one would have been entering your ATM IP address into the Companion setup so I didn't mention that. 

Glad you've got it working now.
