### ISSUE TITLE
Change Picture in Picture: Position or slide

### ISSUE THREAD

**Issue by Scyten** [bitfocus/companion-module-bmd-atem#106]
I am missing possibility to change the PIP(Picture in Picture position, move the pip or do a pip to fullscreen transition.
Setting the position once an using the buttons a the bottom of this pictures would work for me. 

![image](https://user-images.githubusercontent.com/16176275/104311871-20812080-54d6-11eb-83b6-6b02e2ef2853.png)

**Comment by Julusian** [comment]
Duplicate of #132
