### ISSUE TITLE
2 instances of Supersource1 on Constellation

### ISSUE THREAD

**Issue by ely105** [bitfocus/companion-module-bmd-atem#108]
Using bf 2.1.2 on an ATEM Constellation we were trying to do a "ATEM - set input on preview" and choose SuperSource2.  But there are 2 instances of SuperSource1 in dropdown but both only set SS1 on PVW.

**Comment by Julusian** [comment]
Duplicate of #103, #88, #107

This is fixed in the 2.2.0-77ba794-2756 beta build and newer
