### ISSUE TITLE
Can't connect to my ATEM Mini Pro ISO

### ISSUE THREAD

**Issue by WardCameron** [bitfocus/companion-module-bmd-atem#109]
I'm running version 2.2.0-63c8a70-2795. It won't connect to my ATEM Mini Pro ISO. The ATEM works fine on my network. I have set the IP in Companion to match the IP of the ATEM. It was working with version 2.1.2-f4bcaf3 but no longer. I had to upgrade to get VLC to properly work. 

 I can also ping it on the network, so I know the network is connected. 

I'm running ATEM Control Software version 8.5.2.

Any help is appreciated

![image](https://user-images.githubusercontent.com/77550151/104829146-22c4e100-582e-11eb-9fcd-d0f6bee091e2.png)

**Comment by WardCameron** [comment]
Here's my Companion Config Screen

![image](https://user-images.githubusercontent.com/77550151/104829187-80592d80-582e-11eb-8535-1aa64171f150.png)

**Comment by Julusian** [comment]
Fixed in companion-2.2.0-c81e24b-2796

**Comment by WardCameron** [comment]
Thank you so much. It's connecting perfectly now.
