### ISSUE TITLE
ATEM Mini Dynamic names of Media Pool

### ISSUE THREAD

**Issue by WardCameron** [bitfocus/companion-module-bmd-atem#110]
Your new build fixes the connection with my ATEM Mini Pro ISO, but when I use custom code in my Companion App, it no longer updates with the name of the media in the ATEM Controller Media Pool. The code I'm using is: $(atem:still_1) in the text field. 

Thank you for all you do.

**Comment by Julusian** [comment]
I've just given this a try myself and the variables are updating as expected.
What atem firmware version are you running? It shouldn't have broken, but it is possible

**Comment by WardCameron** [comment]
I'm using the v8.5.2 which is the latest for the ATEM Mini ISO Pro which I run. I'm running Companion v2.2.0-c81e24b-2796-win64. Perhaps I'm setting the button up incorrectly. Here is a screen capture of my Companion setup as well as my ATEM Controller app with the media library open. 

Finally, I've added an image showing Companion with it's web buttons open so you can see I'm still only seeing $NA. 

I appreciate your help. 

![image](https://user-images.githubusercontent.com/77550151/105608056-f09c0d80-5d5e-11eb-9981-079de05afa2d.png)

![image](https://user-images.githubusercontent.com/77550151/105608077-0ad5eb80-5d5f-11eb-935b-f6be49e3f9ea.png)

![image](https://user-images.githubusercontent.com/77550151/105608126-5ab4b280-5d5f-11eb-99a2-7643fb13a6c9.png)

**Comment by Julusian** [comment]
Ah that makes sense, I am glad you figured it out :)

It wasnt that you selected the model, but that you changed the label field in the instance config. That field is what companion uses as the prefix for variable names
