### ISSUE TITLE
Will not connect on Pi

### ISSUE THREAD

**Issue by Jonhug82** [bitfocus/companion-module-bmd-atem#111]
When I run an upgrade on the Pi I get the following error

warning Resolution field "threadedclass@0.8.4-nightly-feat-asar-shim-20210117-132506-5cf608b.0" is incompatible with requested version "threadedclass@^0.8.0"

Module will now not connect to the ATEM

**Comment by JeffreyDavidsz** [comment]
Did you update the node version also? That would be needed, my guess

**Comment by Julusian** [comment]
that warning is expected and unimportant.

@JeffreyDavidsz the yarn update command will error and wouldnt get as far as producing the above error if the node version was wrong

@Jonhug82 Is any logging being produced in the terminal when you run companion? If it is running as a service Im not sure how to find that

**Comment by Julusian** [comment]
I can confirm that it should work, I just updated my pi to the latest and it is connecting.
It sounds like it used to connect for you before updating?

**Comment by Jonhug82** [comment]
Hi Julusian, I just ran the updater again and now its working so not sure what had happened. I could not get it to connect at all yesterday and nothing else has changed. Thank you for checking so quickly.
