### ISSUE TITLE
Atem mini pro iso

### ISSUE THREAD

**Issue by glangiu** [bitfocus/companion-module-bmd-atem#121]
Collego il mio Atem  a Companion e faccio le mie configurazioni, stacco tutto vado in un altra rete collego gli hardware accendo i software ma companion non si collega ad Atem

**Comment by Julusian** [comment]
Does the atem software control work when usb is disconnected? If not then look into resolving that first.

Maybe check if the ip address and subnet the same in both places or if it needs updating?
