### ISSUE TITLE
Swedish characters (åäöÅÄÖ) in dynamic variables does not work

### ISSUE THREAD

**Issue by Gartom** [bitfocus/companion-module-bmd-atem#123]
If an input in the ATEM TVS HD is named using Swedish characters (åäöÅÄÖ), they do not show up correctly when variables, e.g. $(ATEM:long_1), are used as button text.

I don't recall the exact text that show up and I don't have access to the switcher right now. It should be obvious when testing, though.

**Comment by Julusian** [comment]
fixed in the latest beta
