### ISSUE TITLE
Atem Mini Extreme ISO

### ISSUE THREAD

**Issue by BrianGilbert** [bitfocus/companion-module-bmd-atem#125]
Just wondering if full support for the Extreme ISO is coming?

<img width="686" alt="Bitfocus Companion - Admin 2021-03-18 19-17-36" src="https://user-images.githubusercontent.com/114017/111594008-a7c47a80-881e-11eb-8dd2-60765972c217.png">

**Comment by McHauge** [comment]
@BrianGilbert It should work in the 2.2.0 betas, it got added a week or two ago.

**Comment by BrianGilbert** [comment]
Ah, I'll check that in the morning, and confirm

**Comment by BrianGilbert** [comment]
Just Confirming the Extreme ISO is listed and device added without error. thanks.
