### ISSUE TITLE
TV Studio pro 4k

### ISSUE THREAD

**Issue by haeleng** [bitfocus/companion-module-bmd-atem#126]
Hi,
I have a Blackmagic TV Studio pro 4k device
When I try to connect to the TVS studio pro 4k, I get an error.
When I select as device a TV Studio HD (while the hardware is a TVS pro 4k) it does connect without error and works
Could you fix this?

**Comment by Julusian** [comment]
This has been long fixed in the beta builds.

**Comment by haeleng** [comment]
When are these beta builds released as mature.
Is a module automatically updated within companion?

regardss Henk Levels

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
03/19/21,
05:29:33 PM

Op vr 19 mrt. 2021 om 17:20 schreef Julian Waller ***@***.***
