### ISSUE TITLE
Atem Mini Extreme does not connect

### ISSUE THREAD

**Issue by Vyrri74** [bitfocus/companion-module-bmd-atem#128]
Hi.
Facing a connection issue with new Atem mini extreme. Anybody else similar?
![Extreme connecting](https://user-images.githubusercontent.com/81258363/112198388-b7283700-8c15-11eb-9d82-83c12ee2f534.jpg)
Mini extreme firmware 8.6 (first one with Extreme support)
![image](https://user-images.githubusercontent.com/81258363/112198609-f8b8e200-8c15-11eb-80f8-bae49c4a07a4.png)

**Comment by McHauge** [comment]
@Vyrri74 how is it connected, companion only does Ethernet´, also is your ip's setup correctly, can you provide an image of the IP setup in the atem software, and the config page in companion

**Comment by aaronbeaver** [comment]
@McHauge I am having the same issue. I have atem mini pros that connect fine but my extreme does not connect.

**Comment by McHauge** [comment]
@aaronbeaver you're also on the newer beta's right? well I don't have one myself, but I have seen both normal mini extremes and mini extreme iso's connected and running, but that might have been on a build that's a week or 2 old, and not a current one. if you have control over the mini via the atem software on the same pc (without the USB-C connected), then you should be able to do it with companion too. if not then networks is the most likely error.

BUT there is a catch, remember all Black Magic gear has a very low limit of connections they allow over the network, and on "consumer" gear it's a max of 3 network connections at once (if I remember correctly) so the atem software takes one of them, companion another, then you only have space for one iPad or phone or whatever else you need.

**Comment by Vyrri74** [comment]
@McHauge well, in my case there is only 2 network connections to extreme, atem sw control and companion. I am also able to use smaller mini at my friends place. Same network subnet, only different target ip. Mini works fine...

**Comment by Julusian** [comment]
Unfortunately I don't think I have enough information here to try and work from.

I do not think this will be specific to the extreme, it must be either an issue with the connection between your machine and the atem, or companion on your machine not liking atems.

I don't have an extreme to test with, but the mock extreme I have connects just fine, and I havent experienced any connection issues with any of the real atems I have. Also many people are able to connect to their extremes just fine, so if this module is doing something wrong it is going to be hard to replicate
