### ISSUE TITLE
ATEM Mini Extreme Macros not working

### ISSUE THREAD

**Issue by lukastheonly** [bitfocus/companion-module-bmd-atem#129]
I am using the latest companion beta build: companion-2.2.0-a1929525-3172-win64.exe

As far as I can tell, companion does not playback macros on the new Atem Mini Extreme.
I get the Name of the macro into companion, but I cannot playback.

Thank you for looking into this

**Comment by lukastheonly** [comment]
Got it, the preset does not work correctly, but if I manually ad the run macro action, it does work.

**Comment by Julusian** [comment]
Do you know what the preset is setting up wrong?
I don't think I have done anything to this in ages, but it looks correct to me
