### ISSUE TITLE
Atem Mini Extreme - or any Atem Mini with upstream keys, request for Companion to control the upstream key in preview

### ISSUE THREAD

**Issue by samurai-goldfish** [bitfocus/companion-module-bmd-atem#130]
When I put in the Atem Mini, I can put the upstream key onair but I can't get the upstream key in preview mode without using a macro. I would like to request the ability to have that feature.

**Comment by Julusian** [comment]
I think these are what you are looking for
![image](https://user-images.githubusercontent.com/1327476/113577410-2429cc80-9619-11eb-8f94-0bbfa1f3de71.png)

**Comment by samurai-goldfish** [comment]
> I think these are what you are looking for
> ![image](https://user-images.githubusercontent.com/1327476/113577410-2429cc80-9619-11eb-8f94-0bbfa1f3de71.png)

That looks awesome.. Can I try it?

**Comment by Julusian** [comment]
This is in the 2.2 betas for many months
