### ISSUE TITLE
ATEM STUDIO HD Audio control

### ISSUE THREAD

**Issue by frankleggett** [bitfocus/companion-module-bmd-atem#131]
Is it possible to add audio control of the ATEM such as:
Mute Input
Fade Audio Up on an Input
Fade Audion Down on an Input

**Comment by Julusian** [comment]
This is all already possible in the 2.2 beta builds
![image](https://user-images.githubusercontent.com/1327476/113570098-8ed40b80-960b-11eb-969e-4c42bf2e8bc0.png)
