### ISSUE TITLE
Reset Audio Peaks 

### ISSUE THREAD

**Issue by visicor** [bitfocus/companion-module-bmd-atem#133]
It would be great to be able to reset the audio peaks at the push of a button. Sometimes we hit the peak during testing, but would like to use it to monitor levels during the show.

I found this in the API...

**IBMDSwitcherAudioMixer::ResetAllLevelNotificationPeaks method**
The ResetAllLevelNotificationPeaks method resets peak statistics to zero for all original audio mixer inputs and outputs.

**Syntax**
HRESULT  ResetAllLevelNotificationPeaks (void);

**Parameters**
none.

**Comment by Julusian** [comment]
This is now implemented
