### ISSUE TITLE
Request Constellation 8K Output assignment

### ISSUE THREAD

**Issue by rlights** [bitfocus/companion-module-bmd-atem#134]
Request to be able to assign outputs on Constellation 8K.

The Constellation has a matrix between its internal engines & physical outputs so you can route any source or destination to any output.

It would be very useful to do this from Companion, to quickly assign a particular source to a hardware recorder, or as a simple aux output.

**Comment by Julusian** [comment]
This is already possible. The actions and feedbacks refer to 'aux' instead of 'output' for legacy reasons.
Ill look at adding 'output' into the names to make them more findable

**Comment by jlnstglr** [comment]
@Julusian I didn't get it.

in the Action Menu there is a Aux Dropdown, but there are only 3 Aux to choose and in the Input Dropdown there are question marks and no options.

**Comment by Julusian** [comment]
I sounds like it either isn't connected to an atem or failed to detect the model.
Have you tried selecting your model in the settings for the connection?
