### ISSUE TITLE
ATEM transition from Streamdeck disrupted

### ISSUE THREAD

**Issue by mvdussen** [bitfocus/companion-module-bmd-atem#136]
We are using Blackmagic Atem HD TV Studio with Companion and Streamdeck. With Windows 10 PC.
Regularly the transition function between preview and live stops. After trying, we found that in such case we need to pull out the Streamdeck USB plug from the  the PC anmd put it back in. Then it works again. We cannot find the logic, where this is very annoying. Any idea how to solve this?

**Comment by Julusian** [comment]
What version of companion are you running?
In the log, is it reporting each button press as happening multiple times?
