### ISSUE TITLE
Variables for Audio states

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion-module-bmd-atem#140]
Hey everyone,

It would be great to have variables for the fairlight audio inputs to be able to use them with triggers (and for status info on the stream deck)

e.g. $(atem:audio_input_1) returns State on/off for input 1
$(atem:audio_ch_1) returns on/off/AFV for channel 1
Bonus $(atem:gain_input_1) returns db gain (+1.00)

**Comment by eric** [comment]
I would also like variables for the input gain.

**Comment by Julusian** [comment]
handled by #200
