### ISSUE TITLE
Not able to connect to ATEM Mini

### ISSUE THREAD

**Issue by Yuri2009** [bitfocus/companion-module-bmd-atem#141]
Hi there,

have a problem with connection. ATEM Mini found but no access.

I have MacOS Catalina.

Thank you in advance for support.

Yuri

![Screen Shot 2021-05-19 at 04 21 27](https://user-images.githubusercontent.com/74712181/119205901-d517e980-ba56-11eb-9f1c-d038f42941d7.png)

![Screen Shot 2021-05-19 at 04 21 27](https://user-images.githubusercontent.com/74712181/119205719-44410e00-ba56-11eb-8759-7a9f7937837e.png)

**Comment by reneheesen** [comment]
Atems only support control via ethernet.

**Comment by gmaisto2000** [comment]
Hi there,

have a problem with connection. ATEM Mini found but no access.

I have MacOS Catalina.

Thank you in advance for support.
![Screen Shot 2021-05-29 at 11 05 55 AM](https://user-images.githubusercontent.com/85149632/120268699-4f751480-c274-11eb-8f5d-5f30f943711f.png)
![Screen Shot 2021-05-29 at 11 07 19 AM](https://user-images.githubusercontent.com/85149632/120268725-5c920380-c274-11eb-8ee3-b105a8b8a993.png)
![Screen Shot 2021-05-29 at 11 07 36 AM](https://user-images.githubusercontent.com/85149632/120268731-5ef45d80-c274-11eb-845a-8420644545e9.png)

George Maistoi
