### ISSUE TITLE
Request / variable from SuperSource

### ISSUE THREAD

**Issue by raydjee** [bitfocus/companion-module-bmd-atem#142]
Hello,

I would love to have the following variables available (excuse me if it exists already):
- SuperSource box 1 input
- SuperSource box 2 input 
- SuperSource box 3 input
- SuperSource box 4 input
- SuperSource box 1 Active Status
- SuperSource box 2 Active Status
- SuperSource box 3 Active Status
- SuperSource box 4 Active Status

I am considering to use these as triggers. Would that be possible?

**Comment by Julusian** [comment]
I am unlikely to do this, as it will be redundant once https://github.com/bitfocus/companion/pull/1604 is merged which should be soon

**Comment by Julusian** [comment]
That is merged, so I dont think this is necessary anymore. But do say if they are wanted as variables for other uses
