### ISSUE TITLE
Use variables to swap program and pip source back and forth

### ISSUE THREAD

**Issue by panosru** [bitfocus/companion-module-bmd-atem#145]
Hi, I'm trying to make a button that would allow me to toggle the sources between main (aka Program) and PiP.

For example, if the program source is set to Camera 1 and the PiP is set to Camera 3, with a press of a button to be able to switch them.

The variable for the program input is `$(atem:pgm1_input)` and for the PiP is `$(atem:usk_1_1_input)`.

If I have the following actions:

![image](https://user-images.githubusercontent.com/400362/124108687-0da3dd80-da6f-11eb-918e-e5fac571939e.png)

In the input select field, I'm not able to use variables.

Also, in order for this to work an option to set custom variables in actions is also required so that when you press the button the following should happen:

Current state:
Program=Camera1
PiP=Camera3

Press 1
CustomVar=Program (=Camera1)
Program=PiP (=Camera3)
PiP=CustomVar (=Camera1)

Press 2
CustomVar=Program (=Camera3)
Program=PiP (=Camera1)
PiP=CustomVar (=Camera3)

etc.

That way you could be able to swap back and forth the program and pip sources with a single button

**Comment by Julusian** [comment]
I think this is the same as #120
