### ISSUE TITLE
[BUG] Atem Mini Extreme: Set fairlight audio input mix option - Mic 1 and Mic 2 don't function

### ISSUE THREAD

**Issue by JimmyD62** [bitfocus/companion-module-bmd-atem#161]
**Describe the bug**
Atem Mini Extreme: Set fairlight audio input mix option Mic 1 or Mic 2 don't turn off, on, or toggle.   All other inputs function properly.  The Instance feedback for these inputs don't work as well. 

**To Reproduce**

1. Go to "Key Down/On Actions"
2. Click on "Atem Mini Extreme: Set fairlight audio input mix option"
3. Select - Input "Mic 1"
4. Select - Mix Option "On, Off, Toggle"

**Expected behavior**
Mic 1 and Mic 2 should turn on and off

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser EDGE
- Companion Version 2.1.3

**Additional context**

**Comment by Julusian** [comment]
This is working fine
