### ISSUE TITLE
ATEM Extreme Fairlight Headphone Options

### ISSUE THREAD

**Issue by lukastheonly** [bitfocus/companion-module-bmd-atem#162]
The ATEM Extreme features a Headphone Output which allows the user to solo a track, to mute the headphone and to adjust the headphone level. I was searching for this feature, but I could not find it. If so it would be very nice if that feature will be implemented. 

Cheers

**Comment by BibraDesign** [comment]
Second that. It would be amazing if we could have a "Solo"-Button (send input to headphone) for each Fairlight audio channel, with Toogle and Feedback.

**Comment by hossboss** [comment]
Ah, yes, I had assumed this stuff was already in there when planning my workflow, then had to pivot a bit. 

I am mixing all audio on an outboard mixer and sending the program mix in on Mic 1 and the engineer's monitor mix in on Mic 2. The monitor mix is program mix plus headset. The idea is that the engineer will be listening to phones plugged into the Mini, and Mic 2 will be usually be soloed. The engineer can then simply unsolo Mic 2 to check the actual program mix. 

**Workaround**
Solo on/off can be recorded in a macro, so I worked around this by recording two macros for solo and unsolo Mic 2 and then calling the macros from a latching button. This works for my case, but it'd take quite a few macros to set up that sort of control across all of the channels, especially if some channels are split audio.

**Comment by smadds** [comment]
Jumping on this request - any update on adding the ability to nudge headphone volume up & down?

**Comment by Julusian** [comment]
This will be in the betas shortly
