### ISSUE TITLE
Adjust USK parameters

### ISSUE THREAD

**Issue by jeason21** [bitfocus/companion-module-bmd-atem#170]
Would be nic to set the parameters for the upstream key the same way as the "Super Source Box Properties" as ATEM Mini and Mini Pro do not support Super Source and picture-in-picture is done via key.

**Comment by jeason21** [comment]
Added to #132

**Comment by gege107** [comment]
I would love to get that functionnality too. It is available in the SDK.
Would be great.
Thanks
