### ISSUE TITLE
Status Connecting but doesn't[BUG]

### ISSUE THREAD

**Issue by WaybackSessions** [bitfocus/companion-module-bmd-atem#172]
All updated software & first time installation/connection. On Mac via Chrome. Status is connecting but doesn't switch to green/OK for hours. manually input the IP address from BlackMagicATEM. That has never changed with the many restarts to the computer and the internet reset (seems odd?). 
companion 2.1.4
BM ATEM at 8.6.4
Chrome & Safari browsers give the same results.
StreamDeck software has not been downloaded but the hardware is plugged in.

**Expected behavior**
Expect to have status update to OK

**Comment by Julusian** [comment]
Check the ip address you have set in companion, matches the atem. Additionally, it should be in the same range as the ip address of your machines network interface (first 3 blocks should match, last block will be different eg 10.0.0.5 and 10.0.0.10)

With the usb to your atem disconnected, does the atem software connect?

**Comment by WaybackSessions** [comment]
The IP addresses do "match up"
"With the usb to your atem disconnected, does the atem software connect?"  
answer: no

**Comment by Julusian** [comment]
> "With the usb to your atem disconnected, does the atem software connect?"
> answer: no

This doesnt sound like a bug then, and sounds like an issue with either the ip addresses or your network setup.

This comes up almost weekly on the facebook group. I suggest you read through some posts there to help you fix it https://www.facebook.com/groups/2047850215433318/search/?q=atem

**Comment by WaybackSessions** [comment]
Thanks for the guidance!!
