### ISSUE TITLE
Feature request: capture actual Supersource values

### ISSUE THREAD

**Issue by lestrobl** [bitfocus/companion-module-bmd-atem#178]
There would be a massive improvement, if there would be a button which reads out the actual Supersource parameters from the Atem and writes it to a button preset in companion.
At this time, we often do th adjustment of the supersources directly on the mixer and have to manually copy all the parameters (and that can be a lot) into the companion button.

**Comment by Julusian** [comment]
This would be nice, but is dependant on some support on doing this from companion itself: https://github.com/bitfocus/companion/issues/1001

**Comment by Julusian** [comment]
This has been possible for a while
