### ISSUE TITLE
Atem tvs hd audio pan

### ISSUE THREAD

**Issue by andrewfmitchell** [bitfocus/companion-module-bmd-atem#180]
There is a preset for xlr 1 but no xlr 2.
ATEM studio have xlr channel 1 and 2 inputs and I need to be able to adjust the gain as well as mute the mic

**Comment by Julusian** [comment]
Which atems? 'ATEM studio' could mean any of 7 models, which vary between two different internal audio mixers

**Comment by Julusian** [comment]
I am 90% sure that model only exposes the xlrs as a stereo pair, but I shall check.
Could you check if it is possible to do what you want in the atem control software? If it isnt possible there, then it wont be possible to make companion do it.

**Comment by andrewfmitchell** [comment]
I can't mute the left and the right independently ... but I can pan left or right ... which would do what I want. Any chance we can get an option to toggle the left and right or apply a value of the left and right channel?

**Comment by Julusian** [comment]
This will be in the betas soon
