### ISSUE TITLE
ATEM T-Bar Position in variable

### ISSUE THREAD

**Issue by joshnortheimer** [bitfocus/companion-module-bmd-atem#184]
i'd like to be able to store the current t-bar position in a variable, and also set the t-bar position from a variable. then we can run t-bar transitions from inside companion.  specifically, my use case is that we are buying a new constellation hd switcher, and until we have the budget to buy a control surface, i'm using our old atem switcher as a control surface. the t-bar is the only main function i haven't been able to link.

**Comment by Julusian** [comment]
This is in the next beta
