### ISSUE TITLE
Feature request - to invert trigger conditions

### ISSUE THREAD

**Issue by smadds** [bitfocus/companion-module-bmd-atem#185]
I would like to be able to add a condition to a trigger that a keyer is NOT on air. Would it be possible to add this invert option to the trigger condition code?

**Comment by jamiekohns** [comment]
or, add a feedback condition for "Tally:Off"

**Comment by mrsydster** [comment]
Created a pull request for this. Needed this as well to create auto follow video using the M32: 
https://github.com/bitfocus/companion-module-bmd-atem/pull/210

**Comment by Julusian** [comment]
This is now implemented
