### ISSUE TITLE
allow variables in ME and Input fields

### ISSUE THREAD

**Issue by joshnortheimer** [bitfocus/companion-module-bmd-atem#187]
with regards to functions such as "atem: ME: Set Preview input", i'd like the ability to have the ME and Input fields be variables, so that i can have a set of radio buttons that selects the ME, and use the same input select buttons. for instance:

button 1.2 sets custom variable atemME to 1, button 1.3  sets it to 2, etc,

button 1.9 uses "atem: ME: Set Preview input" with the ME value = atemME and input = input1.

**Comment by rjurden** [comment]
I would like to piggy back on this request for the option to set Aux inputs from a stored variable.

Use case: A trigger stores the current Aux configuration to a set of Companion internal variables when a certain input is put into program. When that input leaves program, another trigger reads the internal variables and re-configures the Aux configuration to the same as it was before the first trigger ran.

**Comment by LYMPIA** [comment]
Yes, that could be nice to be able to allow custom variables in the ATEM/BMD/HYPERDECK/WEBPRESENTER... environnement.
This would mean more pratical solutions to generate controls/feedbacks/selections for multiviews, inputs, clips, outputs... etc. etc.
+1

**Comment by jalmar2000** [comment]
I didn't read this post yet but I have also added an issue which has kind of the same request. Did any of you already find a solution tho this.

**Comment by Julusian** [comment]
This is now possible for aux/outputs, me program and me preview. There is a new action for each of those which uses text fields and accepts variables
