### ISSUE TITLE
Feature request - allow Mask configurations for upstream and downstream keys

### ISSUE THREAD

**Issue by darinpope** [bitfocus/companion-module-bmd-atem#190]
I'm actually working on this right now, but I wanted to have a place to track the conversation for the "right" way to implement it. 

Right now, I've got all 5 values in one action:

- enabled
- top
- bottom
- left
- right

However, my gut is telling me to have two separate actions. One for:

- enabled

and one for:

- top
- bottom
- left
- right

What does everyone else think?

**Comment by Julusian** [comment]
Have a look at what I did for https://github.com/bitfocus/companion-module-bmd-atem/blob/master/src/actions.ts#L968-L1009.
Essentially, there is a multi-select dropdown which chooses which fields you wish to set, and then based on the selected fields the 'isVisible' functions on each input will show/hide each input, and when executing it will only set the selected properties

I suppose that could also have been done for https://github.com/bitfocus/companion-module-bmd-atem/pull/189, but with it being so few properties it feels a bit excessive.

**Comment by darinpope** [comment]
Interesting. Seems pretty straightforward. I'll go down that path.

**Comment by Julusian** [comment]
I believe this is done
