### ISSUE TITLE
Why can not connect to my Atem Mini Extreme ISO

### ISSUE THREAD

**Issue by Aboammar1969** [bitfocus/companion-module-bmd-atem#192]
I tried everything I know and could not get Companion to connect to my Atem Mini Extreme ISO!  The status is always stuck at "Connecting" and never get to "OK".  See screenshot below:
![image](https://user-images.githubusercontent.com/108437828/176561100-503c2d67-6665-437b-9892-ac314d52fb37.png)

Here is a screenshot for the setup:
![image](https://user-images.githubusercontent.com/108437828/176561331-0ec4b20c-16e0-4f5b-80aa-948f24c191ea.png)

And here is a screenshot for the IP in Atem:
![image](https://user-images.githubusercontent.com/108437828/176561408-bb59d707-015c-485c-8c84-1f4621111a51.png)

Any idea what is going on?

By the way if I set the network protocol to DHCP in Atem, the IP address  changes to 0.0.0.0 
![image](https://user-images.githubusercontent.com/108437828/176561604-e37d3fbd-1c73-4b63-9853-5e66deffb02a.png)

**Comment by sierrax369** [comment]
You need a working dhcp server in the network you use.
ip 0.0.0.0 is standing for the whole WAN and should replaced after a moment with the DHCP Address or a 169.254.x.x address. If not could try to do typical trouble shooting... and e.g. a factory reset

**Comment by Julusian** [comment]
Yeah, I am 99% sure that this is a problem with network configuration not being correct
