### ISSUE TITLE
audio big issue on constellation HD 2/ME

### ISSUE THREAD

**Issue by Rik83** [bitfocus/companion-module-bmd-atem#202]
Each time I mix the sound via the bmd software, the atem module on companion freezes. I have to disable and enable it again in order to work. 
NOTE : Some of my input are set to separated audio
All the rest is workink perfectly fine

**Comment by Julusian** [comment]
And what version of companion?

**Comment by Rik83** [comment]
I move faders on the atem software and.. boom ! the module atem is frozen on companion (pushing a button on the streamdeck does not do anything)
So in companion, I disable the module, wait maybe 20 seconds and then I can re-enable it.
Same thing in an other way : I program a button on sstreamdeck to mute or unmute an atem input and boom again. I have to disable then enable again
All the others modules are still working and are not affected
It only concerns audio. For all the rest (mixing, macros etc...) there is no problem at all.

For information : I tried the central.io software to control the atem and playing with audio make some issues too...

Atem constellation HD 2/Me
Companion Version: 2.2.3 (the last stable) it is not a beta


Eric EMMANUEL
06 49 44 12 10
videociel.com<http://www.videociel.com/>



De : Julian Waller ***@***.***>
Envoyé : mercredi 3 août 2022 18:14
À : bitfocus/companion-module-bmd-atem ***@***.***>
Cc : Rik83 ***@***.***>; Author ***@***.***>
Objet : Re: [bitfocus/companion-module-bmd-atem] audio big issue on constellation HD 2/ME (Issue #202)


Which things are you changing on the atem?
Moving faders? Muting and unmuting? Something more?

-

**Comment by Julusian** [comment]
I think I can see what is happening here. I have a fix, to be pushed to the betas shortly
