### ISSUE TITLE
ATEM Constellation 8K causes Companion to crash

### ISSUE THREAD

**Issue by NationsProd** [bitfocus/companion-module-bmd-atem#204]
Every time the IP address is added for the ATEM Constellation 8K the entire companion app crashes. The studio 4K switcher connects and works. It is just the Constellation that won't work.
I have tried to select the model, auto detect, as well as every constellation model available on the drop down menu.

There is no code given when companion crashes.
I tried using Companion 2.2.3, as well as the Beta version 2.3.0
The ATEM Constellation is on version 8.6.2, however I tried version 8.6.0 as well

**Comment by NationsProd** [comment]
We have figured out that whenever the Atem Control software is open it causes companion to crash, so when the Atem Control software is closed on every computer then companion works with it and does not crash

**Comment by Julusian** [comment]
strange, I have never encountered this issue on any model before. I expect that a majority of users will have both companion and the software control open simultaneously..

It feels like something else is going on, but I have no idea what

**Comment by Julusian** [comment]
I cannot reproduce this with other models, and I don't see that there would be anything unique about the 8k that could cause this.

As there have been no other reports of this, perhaps it was something unique about your environment, or was fixed as part of another change in a newer version
