### ISSUE TITLE
Add the ATEM's IP Address as a variable

### ISSUE THREAD

**Issue by seanmcnally98** [bitfocus/companion-module-bmd-atem#206]
Would love to be able to call the IP address of the switcher via a variable. This could be something like $(atem:ip_address).

Mainly, this would be useful to pass the IP address into batch scripts. For example, I use several batch scripts which can upload images to my ATEM mini (using [atemlib](https://github.com/mintopia/atemlib)), which I call from Companion. These scripts require the IP address of my ATEM. I could hardcode them within the .bat files themselves, but each time I change locations/networks, I'd need to edit each of my (many) scripts. It would be way easier to just change the IP of the ATEM in Companion, and then pass that as a variable to the script when I run it as a Shell Path button in Companion.

This could also be used for quickly glancing at the ATEM's IP on a button, or passing it to some other connection so they can communicate directly.

**Comment by Julusian** [comment]
This is now implemented
