### ISSUE TITLE
Can't Select ME1 Program for ME2 Preview

### ISSUE THREAD

**Issue by quickestpastor** [bitfocus/companion-module-bmd-atem#207]
I am using bit companion with ATEM 2 ME Production 4k.   I can't select the ME 1 Program (or Preview) for the ME 2 Preview. The drop down menu contains Items for the ME2 Program and Preview, which seems incorrect if you are selecting a source for ME2.

**Comment by krocheck** [comment]
This is correct behavior.  On BMD switchers you can't pick a lower ME from an upper ME.  On a Constellation, ME 4 can't use any 1, 2, or 3 PGM/PVW as source; ME 3 can only use ME 4 PGM/PVW as source.  In terms of ME 2 showing in the list for ME 2, the switcher should reject that if it were sent.  The dropdowns aren't "smart" in the sense that they change the lists based on if the ME selected is either M/E 1 or M/E 2.
