### ISSUE TITLE
[Feature request]: Select headphone monitoring channel

### ISSUE THREAD

**Issue by NickKHarrison** [bitfocus/companion-module-bmd-atem#208]
Would be greatly helpful if the Fairlight monitoring buttons for each audio channel in the Audio page of the ATEM Software Control could be changed via Companion (the round buttons with the headphone icon). This would allow quick monitoring of each channel via Companion (great for live events) and a 'Mix-Minus' style approach to talent recording and playback.

**Comment by Julusian** [comment]
This will be in the betas shortly
