### ISSUE TITLE
Peak Reset and adjust master gain not working

### ISSUE THREAD

**Issue by BoguschMedia** [bitfocus/companion-module-bmd-atem#211]
hi, I found the funktion to reset the Audio Peaks but it doesnt work. If i click on the peaks in the ATEM Software they are resetted in the Multiview but not if i use "Classic Audio: Reset peaks". 
Also "Classic Audio: Adjust master gain" is not working for me. Adjusting a input (xlr for example) works fine!

may be there were updates from blackmagic side in the "classic audio"-commands-stack?

i'm using Companion stable (2.3.1 of today) and beta (also from today 2.4.0) for testing with my Atem Television Studio HD (FW 8.1.1).

**Comment by Julusian** [comment]
This is now fixed
