### ISSUE TITLE
atem mini extreme iso/ wont connect to companion

### ISSUE THREAD

**Issue by makensense** [bitfocus/companion-module-bmd-atem#220]
I enjoy using the companion software , it was working perfectly previously, however I noticed that the Mini ISO had upgraded to version 8.6.1 and the  companion details specify that its preferably compatible with Mini Extreme ISO version 8.6.0, well I downgraded to version 8.6.0 on my Mini Extreme ISO and I an still not able to connect to Mini Extreme ISO to companion.

I would appreciate any relevant feedback

**Comment by Julusian** [comment]
This sounds like a configuration issue, not an issue with the module. If this is still a problem you will get more help on facebook
