### ISSUE TITLE
Preset Style issue in module edit

### ISSUE THREAD

**Issue by AndrewApi** [bitfocus/companion-module-bmd-atem#221]
Running on Pi

Companion version [2.4.0 (2.4.0+4812-beta-e8ffe7e4)

Switching to Short Names and then back to Long Names keeps the the Short Names still (select under the Preset Style dropdown).

![image](https://user-images.githubusercontent.com/46345232/203965784-0e81a690-a658-4d23-a39e-20dedd8938c2.png)

these previously showed this before changing to Short Names

![image](https://user-images.githubusercontent.com/46345232/203966025-8b39cd81-6e0d-43ad-bbcb-f5beb2590053.png)

Is there an easy way to get this to work?

![image](https://user-images.githubusercontent.com/46345232/203966800-e9bc5056-aea1-4245-bc60-9f0dcd857f55.png)

Many thanks for all the updates and functionally in this module.

**Comment by Julusian** [comment]
This will be fixed in the betas soon
