### ISSUE TITLE
Feedback for Set fairlight audio input mix option not working for OFF

### ISSUE THREAD

**Issue by pgordemer** [bitfocus/companion-module-bmd-atem#222]
Set fairlight audio input mix option, when using the feedback option, the ON condition works and allows me to change the button color. The OFF condition does not seem does not seem to be recognized.

Companion 2.4
Atem Mini Extreme Firmware 8.6.1 with 8.10 software control package.

**Comment by Julusian** [comment]
https://github.com/bitfocus/companion/issues/2211

This is fixed in the beta builds, and will be fixed in 2.4.1
