### ISSUE TITLE
AUX Variables: Input ID for M/E1 - 4 

### ISSUE THREAD

**Issue by piedrola** [bitfocus/companion-module-bmd-atem#225]
Hey guys, great to have the AUX Variable options! Thank you.
What's missing in my opinion is an option to change an AUX to one of my M/Es. M/E1 for example has Input ID "10010" but this won't be recognised within the variable field "Input ID". It has no effect to the AUX output that's already set, it stays the same. 

Is it just me who does something wrong or is this option still missing?
Thanks
Piedi

**Comment by Julusian** [comment]
I can confirm that this does work
