### ISSUE TITLE
Set/reset "ISO record all inputs" from companion

### ISSUE THREAD

**Issue by pedanticdan** [bitfocus/companion-module-bmd-atem#228]
This is a feature request.

I would like to be able to change the "ISO record all inputs" from a Stream Deck. As far as I can tell, this module does not currently support that function, although the BMD ATEM api does.

For example, I might want to configure a toggle button to:

Toggle on:

1. set a specific input as the program source
2. set "ISO record all inputs" off
3. then start recording

Toggle off:

1. stop recording
2. set "ISO record all inputs" on

The only thing missing is the ability to change "ISO record all inputs" from companion.

**Comment by pedanticdan** [comment]
I looked through the source, and figured out that the module that provides access to ATEM hardware does not expose access to the "ISO record all inputs" setting. Since it is easy to get the desired function using macros, I'm closing this issue.

**Comment by Julusian** [comment]
It isnt exposed by the library we use simply because there has been no reason to do so yet.

**Comment by davidjoshuaford** [comment]
Except for disk space considerations - I have some long form productions that we just want to capture the PGM for posterity, and ISO recordings would limit the record time before a human needs to step in and data manage. I currently use ATEM Macros to toggle the ISO on/off, so having that native to Companion would be much easier.

**Comment by Julusian** [comment]
This is done and will be in the betas shortly

**Comment by davidjoshuaford** [comment]
Thanks! Will that have the associated feedback to know if ISO is on/off?

**Comment by Julusian** [comment]
@davidjoshuaford yes, there is a feedback too

**Comment by davidjoshuaford** [comment]
Brilliant, thanks!

**Comment by pedanticdan** [comment]
Thanks!
