### ISSUE TITLE
FEEDBACK atem: Fairlight Audio: Audio Mix option does not work very well

### ISSUE THREAD

**Issue by LikeThisReview** [bitfocus/companion-module-bmd-atem#230]
FEEDBACK atem: Fairlight Audio: Audio Mix option does not work very well
It looks like value from the ATEM Mini Pro switcher is taken only at the time of configuring the Feedback, Changing Audio Mix option in Companion works OK but it is not reflected in Feedback.
I'm on Mac Apple Silicon with v3.0.0+5543-beta-0149a38d. Issue is also in previous v3 builds.

**Comment by Julusian** [comment]
This looks like a bug that was fixed in companion 2.4.1, that I forgot to pull into companion 3.0. Itll be in a build shortly

**Comment by LikeThisReview** [comment]
Thanks Julian! When I download build 5544 it refers to build 5543 and
that’s what I see in the GUI. No resolution yet.
When I execute action ‘atem: Fairlight Audio: Set input mix option Camera1
Stereo on’ an existing Feedback does not reflect the action. Adding a new
Feedback results in that the ON state is recognized.

Regards, Nico Wasmus from LikeThisReview

**Comment by Julusian** [comment]
That probably means that it hadnt finished building for you os when you downloaded it. It takes between 10 and 30 minutes to produce a build, with macos being the slowest

Could you try again? It is definitely working for me in 5544.

**Comment by LikeThisReview** [comment]
Many thanks, downloaded 5547 and it works just fine

Op za 7 jan. 2023 om 23:22 schreef Julian Waller ***@***.***>
