### ISSUE TITLE
[BUG] After installing Companion v3.0.0+5627 atem Connection crashed

### ISSUE THREAD

**Issue by LikeThisReview** [bitfocus/companion-module-bmd-atem#232]
After installing Companion v3.0.0+5627 Mac Apple silicon atem Connection crashed on start up.

Log:
system: ** Connection started **
Starting up module class: at
Sentry disabled
Module-host accepted registration
debug: ATEM changed model: 0
ThreadedClass (8312) Skipping exit handler registration as no exit handler is registered
debug: reconnect
info: Connected to a ATEM Mini Pro
system: ** Connection stopped **
system: ** Connection started **
Starting up module class: at
Sentry disabled
Module-host accepted registration
![Scherm­afbeelding 2023-02-04 om 15 42 02](https://user-images.githubusercontent.com/112906760/216774052-4f4bcb4e-3b7b-449c-90b6-bf3541b8b3dc.png)

Regards, Nico Wasmus

**Comment by Julusian** [comment]
Can you click on the `>_` icon in the connections list? 
Then restart the module and provide the log it shows there

**Comment by LikeThisReview** [comment]
Julian,
The log info in my bug report was from that icon.
Clicking on the icon when the module is disabled does not work as it is
greyed out.
Now I have enabled the connection again and clicked on the icon. Then I get
Initializing / Disconnected / Crashed and so on.
system: ** Connection started **
system: ** Connection stopped **
Starting up module class: at Sentry disabled
Module-host accepted registration
debug: ATEM changed model: 0
ThreadedClass (3073) Skipping exit handler registration as no exit handler
is registered
system: ** Connection started **
system: ** Connection stopped **
Starting up module class: at Sentry disabled
Module-host accepted registration
debug: ATEM changed model: 0
ThreadedClass (1102) Skipping exit handler registration as no exit handler
is registered
system: ** Connection started **
system: ** Connection stopped **
Starting up module class: at Sentry disabled
Module-host accepted registration
debug: ATEM changed model: 0
ThreadedClass (9089) Skipping exit handler registration as no exit handler
is registered
system: ** Connection stopped **
system: ** Connection started **
Starting up module class: at
Sentry disabled
Module-host accepted registration
debug: ATEM changed model: 0
ThreadedClass (7871) Skipping exit handler registration as no exit handler
is registered
system: ** Connection stopped **
system: ** Connection started **
Starting up module class: at
Sentry disabled
Module-host accepted registration
debug: ATEM changed model: 0
ThreadedClass (7341) Skipping exit handler registration as no exit handler
is registered
system: ** Connection stopped **
system: ** Connection started **
Starting up module class: at
Sentry disabled
Module-host accepted registration
debug: ATEM changed model: 0
ThreadedClass (802) Skipping exit handler registration as no exit handler
is registered
system: ** Connection stopped **
system: ** Connection started **
Starting up module class: at
Sentry disabled
Module-host accepted registration
debug: ATEM changed model: 0
ThreadedClass (2256) Skipping exit handler registration as no exit handler
is registered
system: ** Connection stopped **

Regards,
Nico

Op za 4 feb. 2023 om 18:00 schreef Julian Waller ***@***.***>:

**Comment by LikeThisReview** [comment]
Installed build v3.0.0.0+5640 and tried to connect again and all works fine! Many thanks! Regards, Nico Wasmus
