### ISSUE TITLE
[Enhancement] Add a variable $(atem:audio_master_faderGain) 

### ISSUE THREAD

**Issue by LikeThisReview** [bitfocus/companion-module-bmd-atem#238]
Please add a variable `$(atem:audio_master_faderGain)` so we can display the result of action 'atem: Fairlight Audio: Adjust master gain' in for example a Text Box. Similar to for example `$(atem:audio_input_1_faderGain)`. 

This is much more convenient then adding feedback 'atem: Fairlight Audio: Master fader gain' for various values.
Thanks. Regards, Nico Wasmus

**Comment by davidjoshuaford** [comment]
I have a similar request – to add ID variable support for Fairlight options: 

```
atem: Fairlight Audio: Set input mix option
atem: Fairlight Audio: Set input gain
atem: Fairlight Audio: Set fader gain
atem: Fairlight Audio: Adjust fader gain
atem: Fairlight Audio: Adjust input gain
```

Being able to select channels by Audio ID number would greatly simplify and reduce the page layout real estate available within 8x4 buttons.

Thanks!

**Comment by issic** [comment]
+1 on This

Add please: 
 
`Atem:Fairlight Audio: Toggle Headphones Solo`
So we can solo channels to headphones for check

`Atem: Fairlight Audio: Adjust Input Delay`
 (as Rotary Function) As we can see in Variable what is the delay, but we can't change it thru Companion

`$(Atem:audio_output_master_faderGain)`
We can't see in Companion what is the Master Output set to, but we can manipulate with it.

`$(Atem:audio_output_headphones_faderGain)`
We can't see in Companion what is the Headphones output set to, but we can manipulate with it.

Fix please:

`Atem: Fairlight Audio: Adjust Monitor/Headphone fader gain` - as it shows "Inputs" and "Source" which is irrelevant (at least for Atem Mini)

**Comment by frabusas** [comment]
Add please:

$(Atem:audio_output_master_faderGain)
We can't see in Companion what is the Master Output set to, but we can manipulate with it.

**Comment by LikeThisReview** [comment]
OK thanks for the explanation

Op do 7 sep 2023 om 23:42 schreef frabusas ***@***.***>:

**Comment by LikeThisReview** [comment]
Many thanks and congratulations with stable version 3.2

Op di 23 jan 2024 om 21:32 schreef Julian Waller ***@***.***>
