### ISSUE TITLE
ATEM T-Bar Control

### ISSUE THREAD

**Issue by bfcmediaguys** [bitfocus/companion-module-bmd-atem#241]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I need to control the percentage of t-bar movement and then reverse the direction to go the other way. 

### Usecases

My church uses side-thirds for some announcements. We build the fly-in from the right side of the screen and I'd like to be able to use the Push DVE feature to a specific amount and then fly it back out the way it came in with some automated t-bar control.

**Comment by dang0ttesman** [comment]
I would also like to have this functionality.

We use ATEMs to overlay two different sources to do live line-ups between two cameras. We'll either use Mix or Wipe to A/B the two sources, and it'd be great to have the t-bar position assignable to a rotary control on the Streamdeck +.

**Comment by Julusian** [comment]
This is in the next beta

**Comment by dang0ttesman** [comment]
hey, I just got the latest version set up and working, and I don't think this is working as expected.

my expectation would be for the rotary control on the StreamDeck + to move the position of the T-bar in a stepped fashion, similar to how a fader control on an audio mixer would work. Turn the knob to the left and it goes down and stops at 0; turn it to the right and it moves up and stops at 100, and with every click on the dial, it'd step say, 5 or 10%.
[Here's an example](https://youtu.be/enNAXN9HnuM?si=Pa9uKzsbKfrH7LgX&t=99) if it's helpful.

Presently, it's only set up to move the T-bar to a specific position - if you set it to 25, when you turn the dial one click it jumps right to 25. So the dials are really only behaving like 2-position switches.

If it's possible to add this functionality, it would be much appreciated!
