### ISSUE TITLE
Feedback Tally:program can't be set to invert

### ISSUE THREAD

**Issue by Restheap** [bitfocus/companion-module-bmd-atem#243]
the box to check is there but is not "checkable"... 
![image](https://user-images.githubusercontent.com/37977494/235167334-07ab7c91-a2bf-4bae-a0ee-6627dfeb8f4b.png)

**Comment by Julusian** [comment]
what version of companion are you on?
I've noticed in 3.1 that checkboxes arent showing the checks anymore, because of some recent experimental changes
