### ISSUE TITLE
Request : Multiview source text feedback

### ISSUE THREAD

**Issue by LYMPIA** [bitfocus/companion-module-bmd-atem#245]
As per aux/output and input source names, could it be possible to get the name of the selected source assigned to a specific window  ?

On ATEM constellation with more than 2 multiviews it would allow the user to quickly display on a single control page every sources assigned to each window per Multiview.

Thanks in advance.

**Comment by davidjoshuaford** [comment]
I second this - multiview source window feedback would help visually speed up routing a layout.

**Comment by Julusian** [comment]
This will be in betas soon
