### ISSUE TITLE
ATEM Television Studio HD8 Iso - No SuperSource

### ISSUE THREAD

**Issue by ruebyi** [bitfocus/companion-module-bmd-atem#251]
Hello,
I found a bug in 3.3.2
ATEM Television Studio HD8 Iso has no SuperSource as Input.

Thank you!

**Comment by ruebyi** [comment]
Is not fixed in 3.0 stable release

**Comment by Julusian** [comment]
Select the HD8 (non iso model) in the config. I don't think companion does anything with the ISO features

Alternatively, this will be fixed in the 3.1 betas shortly.
