### ISSUE TITLE
Add custom variables to Set Stream Key Action

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion-module-bmd-atem#256]
We are working with a platform that generates a new stream key for each event. 

We need the action `atem: Stream: Set service ` to interpret custom variables to automatically update the stream key between events:

<img width="528" alt="Screenshot 2023-08-08 at 9 42 03 AM" src="https://github.com/bitfocus/companion-module-bmd-atem/assets/76959770/1825bfb8-77d1-424b-9f35-ec1effd03660">

Thank you!

**Comment by Julusian** [comment]
This will be in the betas soon

**Comment by davidjoshuaford** [comment]
Awesome, thank you!!
