### ISSUE TITLE
Atem Constellation HD 1ME AUX output issue

### ISSUE THREAD

**Issue by cjba850** [bitfocus/companion-module-bmd-atem#262]
Hi all.

Found a bug with altering the routing for an ATEM constellation HD. For context, remember there are 6 AUX buses (which can also show the PGM bus)

When manually switching the input routed to an AUX output, things are fine for AUX 1

When you change the input on AUX 2, I see the input switch for AUX 3 and AUX 4 in the same button press
If I press the change intended for AUX 3 or intended for AUX 4, there is no change recognised.

Button presses on AUX5 also alter AUX 6
AUX 6 button presses don't make any change

I've double checked the AUX bus recorded for each button - this appears to be a bug in the AUX interface mapping ID's?

Help?

**Comment by Julusian** [comment]
I am not able to reproduce this on a Constellation HD 2ME.
Can you send a screenshot of the actions you are using?

There isnt really any mapping going on here, the atem calls these auxes 0-5 so the only mapping we are doing is subtracting one from the number you specify.

**Comment by cjba850** [comment]
Ah, nevermind - You pointed me in exactly the right direction.

I had a page for each AUX bus (so that you could manually select the input connected for each room. Unfortunately, when I was copying pages, I had updated the AUX bus for the Action, but didn't think to update the Feedback AUX bus at the same time. Looks like after updating the feedback foe each button so that also reflected the AUX in question, all looks right now.

Thank you - and sorry for the trouble!
