### ISSUE TITLE
ATEM HD8 ISO - No Streaming Recording Preset Button

### ISSUE THREAD

**Issue by WaffleTime16** [bitfocus/companion-module-bmd-atem#265]
Building a page for our HD8 ISO yesterday and came to realize that there isn't any options for enabling streaming or recording and no feedbacks available for streaming and recording status or elapsed time.  It is enabled on other ATEMs with the built in encoder such as the ATEM Mini Pro, and it would be great to have it for the larger board as well.

Thanks!

**Comment by Julusian** [comment]
Were you connected to the atem when doing this? And what model was it set to in the config?

If I select that model in the config, then streaming and recording are both available

**Comment by WaffleTime16** [comment]
I just tried again with the ATEM turned on and nothing.  I created another instance to see if maybe it was caching something, because I initially had it set to Auto Detect, but with ATEM HD8 ISO selected, I can't find the Streaming and Recording Preset option.

![image](https://github.com/bitfocus/companion-module-bmd-atem/assets/67638869/1a44f545-df50-4500-a882-74a85cbcc9ab)

![image](https://github.com/bitfocus/companion-module-bmd-atem/assets/67638869/c63e09c2-4722-4336-8809-bbf229f0c20a)

**Comment by WaffleTime16** [comment]
For the record, I do see it for our ATEM Mini Pro ISO- 

![image](https://github.com/bitfocus/companion-module-bmd-atem/assets/67638869/340cba8b-8a2e-49a7-a08f-46d650c6a2da)

**Comment by Julusian** [comment]
What version of companion are you using?
I've also noticed that you are missing presets for aux 2

**Comment by WaffleTime16** [comment]
3.0.0 -rc2

**Comment by Julusian** [comment]
Oh ok. Yeah this is a known bug in 3.0.0 and earlier. Its fixed in 3.0.1 and later

**Comment by Julusian** [comment]
Or tell companion that you are using the non-iso model. We don't do anything for the ISO functionality, and the profile for the HD8 is correct in your version

ref: https://github.com/bitfocus/companion-module-bmd-atem/issues/251
