### ISSUE TITLE
Module should remember last connected model

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-bmd-atem#268]
When on the auto-detect mode, the module should remember what model it was last connected to, so that offline editing works smoother and doesnt default back to the tvs version.

Perhaps the default model should be changed from the tvs to something more modern?

**Comment by davidjoshuaford** [comment]
Perhaps the SDI Extreme ISO could be a good default atem, as it is widely used, and covers 4 out/ 8 in, supersource, multiview, and rec/streaming.
