### ISSUE TITLE
[Request]  Read and Set Timecode from the Atem

### ISSUE THREAD

**Issue by Xtreemtec** [bitfocus/companion-module-bmd-atem#272]
Being able to read the Timecode from the Atem as Feedback.   But also being able to Set the timecode To the Atem.   As many Atems can not handle Time of Day.   It would be great to push a button and let it sync to PC time or NTP.    Or preset time configured.

**Comment by Suenee** [comment]
I also agree with this idea. It would be great to be able to read the timecode of an ongoing recording or live stream.

**Comment by Julusian** [comment]
This is implemented and will be in the betas shortly
