### ISSUE TITLE
Doesn't recognize Constellation 2 M/E [Version 3.2 of Companion]

### ISSUE THREAD

**Issue by pbsargent** [bitfocus/companion-module-bmd-atem#274]

**Comment by Julusian** [comment]
Any more details here?

I have been using this module with a Constellation 2 ME since they started shipping

**Comment by pbsargent** [comment]
I get the following message on the Connections page of the UI when I configure the ATEM module: "Warning
Unknown model: ATEM 2 M/E Constellation HD. Some bits may be missing"

**Comment by Julusian** [comment]
what version of companion?

**Comment by pbsargent** [comment]
I get the message both at 3.2 level of companion and Beta [3.3.0 (3.3.0+6708-main-122cb1be)]
