### ISSUE TITLE
Expose Stream Cache Used as variable

### ISSUE THREAD

**Issue by pedanticdan** [bitfocus/companion-module-bmd-atem#275]
This is a feature request. 

It would be great if companion had access to a variable "stream_cache_used" which contained to data from

IBMDSwitcherStreamRTMP::GetCacheUsed()

It would be handy to be able to track the cache better during a stream, and perhaps create triggers based on the how full the cache is.

**Comment by Julusian** [comment]
This is merged and will be in the betas shortly
