### ISSUE TITLE
[Request] Add Mic 1 & 2 audio delay control

### ISSUE THREAD

**Issue by kornelion** [bitfocus/companion-module-bmd-atem#285]
Hello, 

The idea here is to give hand to control audio delay for Micro 1 and 2 inputs with a drop from 0 to 8 (images)

The use case is the following: i'm using wired hdmi camera and NDI wireless camera. Image delays are obviously different between those two and since i use wireless microphone (rode go) in Mic 1 & 2 inputs, i have to change the microphone delay if i choose the hdmi camera or wireless NDI camera to keep a good lipsync. 

At the moment, i haven't found any options to alter this setting for Mic 1 & 2 inputs. 

Thank you

**Comment by Julusian** [comment]
This is implemented and will be in the betas shortly

**Comment by kornelion** [comment]
Awesome, thanks.
