### ISSUE TITLE
Add "atem: Startup State: Load" capability

### ISSUE THREAD

**Issue by pbseagle** [bitfocus/companion-module-bmd-atem#286]
In the ATEM Companion module I see a command "atem: Startup State: Save". Is there no "atem: Startup State: Load" to allow the setting of an ATEM to a "known state" [assuming one saved the startup state via the GUI?

**Comment by Julusian** [comment]
As far as I can tell based on the official software and the SDK, there is no way to do this. The only solution is to physically power cycle the atem.

So I don't think there is anything we can do for this. If anyone knows of or discovers a way this can be done then this can be reopened.
