### ISSUE TITLE
Add Zoom function to ATEM Camera Control

### ISSUE THREAD

**Issue by rayneram** [bitfocus/companion-module-bmd-atem#288]
The new facilities for Camera Control are working well but are missing control of the lens Zoom function. 

I realise that the necessary zoom functionality is missing from the base atem-connection-camera-control package, but I was able to hack something together fairly quickly to get it working (which hopefully means it shouldn't be too complicated to do it properly!)

**Comment by Julusian** [comment]
Could you share what you have hacked together? 
The reason this hasnt been implemented already is that I am not able to test it (I think its the lense I have which doesnt support it), and I can't be sure that a blind implementation will work or will present sensible numbers.
