### ISSUE TITLE
Set source id with variables for Super Source Art and Art Key

### ISSUE THREAD

**Issue by LikeThisReview** [bitfocus/companion-module-bmd-atem#302]
Want to be able to Set source id with variables for Super Source Art and Art Key as Set Art properties does no support variables and works with source and not source id

Use case is a atem “micro” panel design for 4 M/E Constellation in Companion where on the select bus row the user is able to assign (shifted) sources to supersource boxes (possible) and art / artkey (workaround requires 52 additional steps; in this design sources can be mapped to buttons (so no fixed 1-10 sources)

**Comment by LikeThisReview** [comment]
Furthermore: "Set Art properties" does not allow Color 1 and Color 2 as Sources for Fill, but does accept it for Key Source. This should be the other way around, I suppose.

**Comment by Julusian** [comment]
This will be in the betas shortly

**Comment by LikeThisReview** [comment]
Super !
