### ISSUE TITLE
Add support for USB Webcam Out Source setting

### ISSUE THREAD

**Issue by kanetreble** [bitfocus/companion-module-bmd-atem#305]
From Atem Switchers 9.5 update some ATEM products now support changing USB Webcam Out - it would be great to be able to set this from Companion.

Kind regards,

Kane

**Comment by kanetreble** [comment]
To clarify, this is changing the source of the webcam output

**Comment by themanjotsingh** [comment]
In addition to this, a similar request: It would be amazing if we could also set what inputs/sources are routed to the HDMI outputs 

Thank you!

**Comment by themanjotsingh** [comment]
After some poking around, I have found that the HDMI outputs are AUX 1 and 2, and the webcam output is AUX 3. To add the webcam source change functionality, the model definitions need to have AUX 3 added for the following models:

    ATEM Mini Pro
    ATEM Mini Pro ISO
    ATEM Mini Extreme
    ATEM Mini Extreme ISO
    ATEM SDI Pro ISO
    ATEM SDI Extreme ISO


@kanetreble A temporary solution, until the definitions have been updated, is to manually select a model which has more AUX outputs, to show the AUX 3 option.

**Comment by Julusian** [comment]
Another temporary solution is to use the `Aux/Output: Set source from variables` action, as that will accept `3` to control the webcam output

**Comment by Julusian** [comment]
This will be in the betas shortly
