### ISSUE TITLE
Populate Label 8, 9, and 10 of Input in multiviewer 1 for for ATEM Mini Pro

### ISSUE THREAD

**Issue by LikeThisReview** [bitfocus/companion-module-bmd-atem#307]
Labels "$(atem:mv_1_window_8_input)", "$(atem:mv_1_window_9_input)", and "$(atem:mv_1_window_10_input)" seems to be blank (it looks like it contains 1 non-printable character), while "$(atem:mv_1_window_8_input_id)" = 9102, "$(atem:mv_1_window_9_input)" = 9101, and "$(atem:mv_1_window_10_input)" = 9103. Values populated should be Record Status, Stream Status, and Audio Status.

(Yes, layout of MultiView in AMP is fixed, but in a multi switcher setup in my Companion pages I need these labels. Yes a work around is to do this hard coded).

Many thanks, Nico Wasmus

**Comment by Julusian** [comment]
This will be in the betas shortly
