### ISSUE TITLE
Companion 3.3.1  connection issue to ATEM Mini Extreme ISO (ATEM Software Control 9.5.1)

### ISSUE THREAD

**Issue by btorelli** [bitfocus/companion-module-bmd-atem#310]
I recently upgraded my M1 Max Mac Studio to Sequoia 15 Beta. The upgrade, for the most part, was uneventful in terms of application compatibility. One exception that popped up was that Companion 3.3.1 not longer communicates with my ATEM Mini Extreme ISO or my Hyperdeck Pro Plus. Companion 3.3.1 reports that it is a "Connecting" state but never completes the connection. I use the Companion Plugin on my Streamdeck XL which is totally useless since Companion 3.3.1 cannot communicate with either the ATEM Mini Extreme ISO or the Hyperdeck Pro Plus. I did try Companion 3.4 as a circumvention. No joy. No sure why the connection failure lies. Any help on solving this issue would be greatly appreciated. Finally, I know beta versions of Macos can be troublesome, but past confidence in the Apple beta releases does not stop me from installing the beta versions. For now, I am controlling my ATEM Mini Extreme ISO with Mixeffect (Adam Tow) and this works perfectly.

**Comment by brianteeman** [comment]
I have had possibly similar issues with my atem mini pro.

What has worked for me is to click on the logs icon which open the logs page in a new tab. Then clicking on stop connection. Wait for a response in the logs and then clicking on start connection.

If I keep the logs tab open from then onwards the connection appears to stay connected although there are a lot of timeout and reconnect messages

**Comment by Julusian** [comment]
I shall close this then. Sounds like macos broke something for a bit
