### ISSUE TITLE
Feature request: Add variable/text support to Set Media Player Source from Variable 

### ISSUE THREAD

**Issue by nathanhcooper** [bitfocus/companion-module-bmd-atem#311]
The media player being changed by this action should be optionally a variable. I mainly want to be able to make multiple pages for all the media player items without having to change pages for each media player I'm trying to access as well. If I can make the media player a variable, I only need to make 1 button for each still.
This already exists for auxes as well as M/Es.

**Comment by Julusian** [comment]
This will be in the betas shortly
