### ISSUE TITLE
Latest beta (3.5.0 - 7423) crash

### ISSUE THREAD

**Issue by ChrisSW58** [bitfocus/companion-module-bmd-atem#323]
ATEM connection crashes on MscOS when not attached to ATEM unit. Not a major issue but it didn't crash before :) Unable to provide logs or do anything as the module is on a permanent retry loop.

**Comment by Julusian** [comment]
Is this still happening?

**Comment by ChrisSW58** [comment]
No - all working as it should under 3.5.0 7532. Gets a connection failure (which is correct) but the actions and variables are now available to work with while off-line. Very many thanks.

**Comment by Julusian** [comment]
I've not done anything to the module since you reported this, so sounds like macos being annoying 🤷

**Comment by ChrisSW58** [comment]
Very possibly...or perhaps underlying Companion code changed (don't know enough about the infrastructure to know what code manages what functionality!)
