### ISSUE TITLE
MultiView Quadrant Control

### ISSUE THREAD

**Issue by pbseagle** [bitfocus/companion-module-bmd-atem#334]
The BlackMagicDesign  ATEM control software divides the multi-view into 4 quadrants, each quadrant can either display one source or four sources.  Please update the companion module to reflect this level of control

**Comment by Julusian** [comment]
This has been supported for a while.
The `Multiviewer: Change layout` action allows you to choose how each quadrant is divided. And the `Multiviewer: Change window source` action will change what source is in each box. I don't remember which 'windows' are used when a quadrant is showing a single source, but its one of the ones listed

**Comment by davidjoshuaford** [comment]
1,3,9,11 👍
