### ISSUE TITLE
Start/Stop Recording for BMD Cameras from Camera Control

### ISSUE THREAD

**Issue by taylorcakes** [bitfocus/companion-module-bmd-atem#337]
I am wondering if it is possible to start/stop a camera's recording from this module. I have two Studio Camera 6k and I would like to be able to remotely start recording to their USB drives. I also plan to get some Micro Studio Camera 4k g2 in the future and this feature would be really helpful as they will be in harder to reach locations. Thanks

**Comment by Julusian** [comment]
This is possible as of a couple of weeks ago.

**Comment by taylorcakes** [comment]
Is it possible to see the state of recording as a feedback? I do see the record option, but I wanted to change the button based on the state (e.g. recording/stopped)

**Comment by Julusian** [comment]
Unfortunately not. In my testing (with a micro studio 4k g2) the atem wasn't reporting that information back to us

**Comment by taylorcakes** [comment]
Thanks for the quick reply, I appreciate all your work on this
