### ISSUE TITLE
Not able clone the repo on Windows

### ISSUE THREAD

**Issue by Tomblarom** [bitfocus/companion-module-bmd-atem#341]
I tried to clone this repo on two differnt Windows machines and it always failed with this error:

```
Cloning into 'C:\Users\xxxx\Documents\GitHub\companion-module-bmd-atem'...
remote: Enumerating objects: 3242, done.        
remote: Counting objects: 100% (459/459), done.        
remote: Compressing objects: 100% (159/159), done.        
remote: Total 3242 (delta 370), reused 316 (delta 296), pack-reused 2783 (from 1)        
Receiving objects: 100% (3242/3242), 1.66 MiB | 881.00 KiB/s, done.
Resolving deltas: 100% (2422/2422), done.
error: invalid path 'src/actions/aux.ts'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

Downloading and extracting the .zip leads to an "Internal errror 1" (WinRAR). When normally unzipping, it's always the `aux.ts` file that causes "file has been moved errors":
- `src\action\aux.ts` / `src\action\_aux.ts`
- `src\feedack\aux.ts` / `src\feedack\_aux.ts`
- `src\presets\aux.ts` / `src\presets\_aux.ts`

Cloning with Ubuntu Sub-Linux worked fine. My best guess it's some linking issue, which windows does not understand..

```
Cloning into 'companion-module-bmd-atem'...
remote: Enumerating objects: 3242, done.
remote: Counting objects: 100% (459/459), done.
remote: Compressing objects: 100% (159/159), done.
remote: Total 3242 (delta 370), reused 316 (delta 296), pack-reused 2783 (from 1)
Receiving objects: 100% (3242/3242), 1.66 MiB | 3.53 MiB/s, done.
Resolving deltas: 100% (2422/2422), done.
```

**Comment by Julusian** [comment]
TIL that windows has some ancient rules of certain filenames that can't be used https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

**Comment by Julusian** [comment]
I've renamed those files now.
You won't be able to checkout any commits between january and now, but the latest commit and any future ones should be fine

**Comment by Tomblarom** [comment]
Thanks for addressing @Julusian 😊 I know it's not common, to compile on Windows. Keep up the good work!
