### ISSUE TITLE
ATEM: Supersource and DVE Key box incremental increases

### ISSUE THREAD

**Issue by chriskooken** [bitfocus/companion-module-bmd-atem#36]
**Describe the feature**
Allow for the user to create a directional pad of buttons on the StreamDeck to increment the x&y coordinates, crop and scale by some factor each button press. It would be helpful if this worked for DVE AND Supersource boxes.

**Is this platform dependent (windows, mac, ..)?**
Shouldn't be.

**Usecases**
Positioning super source boxes are a pain. On the ATEM panels, you can use a joystick to move the boxes. If I could replicate that behavior using 4 buttons to position them and every press of the button it moves the box some additional amount (x++) in some direction would be wonderful.

**Comment by Julusian** [comment]
Yeah, I am open to this idea.
I can see it working as a probably new action with mostly the same fields where you specify the difference to apply each press.

Would you want it to repeat while holding the button, or are you happy to have to press repeatedly (the easier one to implement)?

And would you expect presets for these? I am concerned that could result in a lot of presets for the many options at a couple of granularities

**Comment by chriskooken** [comment]
Julusian,

Thanks!
I think repeat while holding would be great. But if thats too complicated, no big deal.

Nah, I don't think we'd need presets for this.

**Comment by chriskooken** [comment]
@Julusian Any chance on getting this done soon? SuperSource boxes are SO painful to position even in the BMD software.

**Comment by Julusian** [comment]
Incremental changes for supersource boxes are available in the latest beta build
