### ISSUE TITLE
Toggle upstream keyers being tied to transition

### ISSUE THREAD

**Issue by videohannes** [bitfocus/companion-module-bmd-atem#39]
I can't find a way to configure a button for the following features of my Blackmagic Design 4ME:

BKGD -> Background in Preview
KEY 1 -> Tie Key 1 to Preview
KEY 2 -> Tie Key 2 to Preview
KEY 3 -> Tie Key 3 to Preview
KEY 4 -> Tie Key 4 to Preview
DSK 1  TIE -> Tie DSK 1 to Preview
DSK 2  TIE -> Tie DSK 2 to Preview

Can't find a way to configure them neither via preset nor via manual button configuration, am I overlocking anything?

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
Not needed

**Usecases**
Useful button ;)

**Comment by Julusian** [comment]
What version of companion are you running?
I think changing the Transition Selection (background + upstream keys) is possible in 2.0.
Setting tie for the downstream keyers has not been asked for so is not implemented.

As a workaround until support is added, you could use a macro

**Comment by videohannes** [comment]
Hi! Thanks for your reply! I am using 2.0.0. 
Do you have a hint where to find the selection for background and upstream keys? I only find the ON AIR for upstream 1-4 but not the KEY.

Would be nice if the DSK Tie could be implemented.

**Comment by Julusian** [comment]
Its an action called `Change transition selection`

![image](https://user-images.githubusercontent.com/1327476/70543563-7e6c6780-1b62-11ea-867f-f0bd68c6dc35.png)

**Comment by videohannes** [comment]
With `change transition selection` I cant just toggle one button, I always select e predefined set of layers. Thats a cool function but unfortunately not what I am looking for.

**Comment by Julusian** [comment]
ah ok, then yeah I dont think that is implemented yet.
its on the list, I might be able to get to it later this week

**Comment by videohannes** [comment]
That would be awesome!

**Comment by krocheck** [comment]
@Julusian I was thinking about this a ways back ... reason being how the broadcast panels operate.  I'm used to press-and-release said desired combination vs. how the software operates as click-toggle.

It could be there is a mode for toggle vs. "multi-select" (panel-like).  My issues was tracking figuring a tracking and slightly lengthened debounce solution to allow for the panel-like functionality.

**Comment by Julusian** [comment]
@krocheck good point, which raises implementing anything for this will need to carefully think about timings to avoid race conditions. Which makes this a bit harder to do than I first thought.

**Comment by quentinmit** [comment]
My PR #41 might address some of this; it adds an action to set a particular part of the transition selection without having to set the whole transition selection.

**Comment by Julusian** [comment]
This is now implemented
