### ISSUE TITLE
Request: Renaming input labels

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion-module-bmd-atem#43]
It would be nice to be able to have a custom text field with new label text for a specific input number. For example, we use Companion to control our VideoHub router and sometimes the source going to an input on our switcher will change, but the label on the multiview won't without editing it manually. The idea for this would be to add an action from the ATEM instance to where we could enter the text for the new input so it changes automatically.

**Comment by Julusian** [comment]
Unfortunately this isn't going to be a quick one to implement.
The upstream atem-connection library does not yet support this https://github.com/nrkno/tv-automation-atem-connection/issues/59 and I don't expect that to happen soon as it is surprisingly complicated to do.

**Comment by apr3ntice** [comment]
The atem-connection library has support for routing inputs in the multiviewer. Is it possible to re-route the window as a workaround to update the label?

**Comment by Julusian** [comment]
This was implemented over a year ago
