### ISSUE TITLE
[Bug] AUTO DSK Transition only activates if DSK is on air

### ISSUE THREAD

**Issue by sakhaUAC** [bitfocus/companion-module-bmd-atem#47]
The "AUTO DSK transition" will only activate if the DSK is already on air. With the DSK off, "AUTO DSK transition" does nothing, with the DSK on, "AUTO DSK transition" will work as intended and AUTO it out. Same issue with DSK 1 and DSK 2 both.

build companion-2.0.0-5e2c920-2061
Stream Deck XL 32-key
ATEM Firmware 8.1, ATEM 1 M/E Production Studio 4K
Windows 10 Pro, 1903 (Build 18362.657)

Was working previously on build companion-2.0.0-8b6d53c-2055, all other specs identical.

**Comment by Julusian** [comment]
This has been fixed in companion for a while
