### ISSUE TITLE
[BUG] Does not update instance status on initial connect

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion-module-bmd-atem#48]
The module does not update the connection status to STATUS_WARNING while connecting, or STATUS_ERROR on disconnected, when you start companion, and the atem is unavailable. I have not tested if it updates correctly when it successfully connects first.

**Comment by bryce-seifert** [comment]
Just tested, it does update if successfully to OK if it connects first. It does not update to warning or error if the ATEM is disconnected after being recognized as connected.

**Comment by Julusian** [comment]
@haakonnessjoen is the expected status behaviour written anywhere? I havent seen anything on the wiki, which is why this is not what you were expecting.

But anyway, this should be as you expect now

**Comment by haakonnessjoen** [comment]
Aha, I see. We should update it then. :) I guess most modules are based on the internal tcp/udp module which have a helper function to update the status. So it’s simply forgotten. I will test tomorrow!

**Comment by bryce-seifert** [comment]
Just did some testing with the build. Seems to be displaying status correctly on connect, reconnect, and disconnect.

**Comment by Julusian** [comment]
Im pretty sure this is fine now, if not reopen and I can take another look
