### ISSUE TITLE
Request: audio mixer input mutes

### ISSUE THREAD

**Issue by njkeever** [bitfocus/companion-module-bmd-atem#51]
I have an ATEM 1 M/E and I'd like to be able to control the audio input mutes. I have different audio sources plugged into both the RCA and XLR jacks, and I use one or the other depending on the situation. Right now I have to open the atem control software, go to the audio tab, and toggle the "ON" buttons for each input. I would also need the buttons on the streamdeck to change color depending on each audio input state so I know which is on and which is off.

**Comment by issic** [comment]
I second that, A mic ON/OFF with a feedback. We using it in School Online studio in the times of Corona and for simplicity this will allow teacher to turn on or off his mic.

**Comment by swperic** [comment]
setting audio fader levels and enable disable AFV per input would be great too! Thank you for reading!

**Comment by Julusian** [comment]
Sorry for the delay, this has been implemented in the latest beta build

**Comment by njkeever** [comment]
Great, thank you so much!

**Comment by Jibun-no-Kage** [comment]
Example of how this is used or done?  Documentation?

**Comment by travmason** [comment]
> Example of how this is used or done? Documentation?

Did you manage to find it? I've been hunting around doco and settings and can't see it anywhere.

**Comment by Julusian** [comment]
You want the `Fairlight Audio: Set input mix option` action

**Comment by travmason** [comment]
> You want the `Fairlight Audio: Set input mix option` action

Awesome thanks that's the one!
