### ISSUE TITLE
Down Stream Key Fade Not Working

### ISSUE THREAD

**Issue by raythompsontn** [bitfocus/companion-module-bmd-atem#54]
I was attempting to define a button to do a fade on BlackMagic Design (ATEM 1) down stream keyer number 2. I was able to make the button work with DSK 1, fade and cut. I then changed the button to do a fade on DSK 2. Nothing happened. Changed the button to do a cut on DSK 2. Worked just fine. Changed back to fade on DSK 2 and nothing happened.

The problem seems to be related, and confined, to using a fade on DSK 2. Cuts work. Fade and cuts on DSK 1 work. Just not fades from DSK 2.

Any way to resolve this issue?

**Comment by Julusian** [comment]
What version of companion and atem firmware are you using? 

This sounds like an issue that was fixed in companion 2.0, which was introduced in atem firmware v8.0.1

Related: https://github.com/bitfocus/companion-module-bmd-atem/issues/38 #32

**Comment by raythompsontn** [comment]
Julian:

 

I am using version 8.1 software on the ATEM. I am using 1.4.0 of the companion software. The only download for version 2.0 that I saw on the website was for the beta version with a cautionary message about not relying on that version to be stable. Beta software is in the process of being developed. Thus I did not consider version 2.0 to be something that should be used in a production environment. To quote “Don't blame us if these builds ruin your show. These are experimental developer builds, and should never be considered show safe. Use at your own risk!”. Sounds alarming and something to be avoided until stable.

 

Ray Thompson

Media Director

Central Baptist Church

**Comment by cjdenio** [comment]
Companion 2.0 is actually *more* stable than 1.4 at this point. I believe the release was delayed due to the coronavirus debacle. It was announced somewhere in the Facebook group.

**Comment by Julusian** [comment]
Yeah, 2.0 is just a little bit of paperwork off being declared stable so it is as safe to use as 1.4 is.

But this is already fixed in 2.0, and there is nothing more I can do on this for you.

If you dont want to update companion, then you could either downgrade your atem firmware, or work around the problem with macros
