### ISSUE TITLE
Need Support For ATEM Mini Pro

### ISSUE THREAD

**Issue by LOVEChen** [bitfocus/companion-module-bmd-atem#55]
When connect device at osx , system get warning
Unknown model: ATEM Mini Pro. Some bits may be missing

**Comment by pucho619** [comment]
Has anyone made an integration for the ATEM Mini Pro? There is no direct options to add the ATEM Mini Pro

**Comment by Julusian** [comment]
You can ignore that warning, or force it to treat it as the normal mini for now.

I have started working on adding a profile (which so far is identical to the mini) and some new functionality but it isn't in the builds yet

**Comment by Julusian** [comment]
This will now be picked up properly, but no support for the new features has been added for now
