### ISSUE TITLE
ATEM Mini Pro Recording Actions

### ISSUE THREAD

**Issue by ericsonjohnson** [bitfocus/companion-module-bmd-atem#57]
Hi,

With the new ATEM Mini Pro, they have the ability to record a stream to a USB/SDD drive. This is awesome and I would love to integrate it into my work flow. I saw in the SDK in Sec.12 they have predefined functions for recording state, errors, and of course start and stop recording. Is this possible to integrate these feature into the companion app? It seems doable but my lack of coding knowledge makes it difficult for me to do anything.
Thoughts??

thanks

**Comment by Julusian** [comment]
This is on my list of things to do, waiting for me to have the time.
Unfortunately, its not a quick or simple task as it requires reverse engineering these new parts of the atem protocol.

**Comment by ericsonjohnson** [comment]
Hmmm is there someway I can help? I do antenna engineering by trade, but I'm sure I can help figure stuff out...

**Comment by Julusian** [comment]
This has been implemented in the latest beta build
