### ISSUE TITLE
Unknown model: ATEM Mini Pro. Some bits may be missing

### ISSUE THREAD

**Issue by gAmUssA** [bitfocus/companion-module-bmd-atem#58]
I'm running 2.0.0 (62b280c-2271) on raspberry pi (official companion image on pi 4 4gb).
Getting this message while adding ATEM mini pro.

also I have this in log UI

```
03. 23:26:15 CORE(cb): db.tmp->db failed: Error: ENOENT: no such file or directory, rename '/home/pi/companion//db.tmp' -> '/home/pi/companion//db'
```

Kindly advise!

**Comment by Julusian** [comment]
A profile for the mini pro was added in 2.0.0-ea17466-2352, if you update to that or newer that warning will go away.

That error would be best reported on the main companion repo, as that is not related to this atem module
