### ISSUE TITLE
Unable to enable the PIP (Picture In Picture) button on ATEM mini

### ISSUE THREAD

**Issue by techbytesrn** [bitfocus/companion-module-bmd-atem#59]
I haven't been able to find a way to turn on/off the PIP button on my ATEM Mini.  I use this feature a lot.  Please advise if I have overlooked how to turn this feature on/off with Companion.

**Comment by Julusian** [comment]
I believe the pip is done on an USK(upstream keyer), and there is an action to set that on or off.
The position presets are not supported

**Comment by Julusian** [comment]
As far as I can tell there is nothing that needs to be done here. Does anyone feel differently?
