### ISSUE TITLE
ATEM Constellation 8K not connect.

### ISSUE THREAD

**Issue by wicherdt** [bitfocus/companion-module-bmd-atem#64]
I use companion beta with stream deck XL.
Companion not working properly with Constealation 8K, only as "4 ME Broadcast 4K" model with firmware 8.1 but GUI Status is always "Reconnecting", but MACROS are working ok.

But firmware 8.1 is buggy (Atem Software don't save chroma color configuration).
When do you plan support higher firmware as 8.2?
I tested 8.2.3 and companion don't connect to ATEM.
(Few days ago i used companion with older 2 ME Production Studio 4K with success.)

**Comment by Julusian** [comment]
What version of companion are you using?
I am not aware of any issues using newer firmware in the companion 2.0 builds, I run mine on 8.2+ and they appear to be fine.

I don't have access to a Constellation myself, so it is hard to test for issues particular to that device. Would you mind running this tool for me against firmware 8.2 or higher? https://builds.julusian.dev/atem/ It generates a file containing the state of your atem, which will let me to use some tools to pretend to be that model

**Comment by wicherdt** [comment]
Companion ver: 2.0.0-4606a41-2356

[Constellation-8.2.3.data.log](https://github.com/bitfocus/companion-module-bmd-atem/files/4772711/Constellation-8.2.3.data.log)

**Comment by mrlad** [comment]
@Julusian , could this constant reconnecting be similar to the continuous reconnecting problem I had with the X32 even though everything was functional.  @wicherdt , I solved my issue by restarting the companion app. At that point, the X32 module stopped the constant reconnecting and connected reliably. 

https://github.com/bitfocus/companion-module-behringer-x32/issues/15#

**Comment by wicherdt** [comment]
I configure "instance" as ATEM with model "Mini Pro" and connecting is OK.
I configure buttons layout from scratch and buttons with macros working OK.
The same configuration with model "Constellation 8K" not working.

**Comment by Julusian** [comment]
I tried companion against a fake constellation last night, and was able to get this happen, but that could be my fake version acting differently. I am working on getting access to the constellation at work to do a bit more debugging into that. 
Did any of the feedbacks work?

@mrlad possibly, but I dont know what a common cause could be except for companion ignoring the device status updates

**Comment by Julusian** [comment]
I realised that it must be something wrong with my fake version, as the dump capture tool worked fine. Which means I dont know what would be causing this.

It is possible that the connection is timing out. What are you running companion on, and what it the network setup like between that and the atem?

Does the log panel in companion say anything about the atem?

**Comment by wicherdt** [comment]
Companion is running on windows 10 with newest updates.
PC and ATEM are connected to LAN and configuration is static IP.
For several days it is more difficult to connect to ATEM.
I must restart companion few times. It is strange, companion read macros numbers but not colors and names. But if is one conected is working all day OK.
The log panel say nothing about errors ATEM. 

23. 11:36:40 instance(atem): Connected to a ATEM Constellation 8K
23. 11:36:37 instance(u0V0GwjnM): Enable instance atem
23. 11:36:35 instance(atem): Lost connection
23. 11:36:35 instance(u0V0GwjnM): Disable instance atem
23. 11:36:10 instance(u0V0GwjnM): Enable instance atem
23. 11:36:09 instance(atem): Lost connection
23. 11:36:09 instance(u0V0GwjnM): Disable instance atem
23. 11:35:48 instance(atem): Connected to a ATEM Constellation 8K
23. 11:35:46 instance(u0V0GwjnM): Enable instance atem
23. 11:35:39 instance(atem): Lost connection
23. 11:35:39 instance(u0V0GwjnM): Disable instance atem

What more can i do to debug this or send more debug logs?

**Comment by Julusian** [comment]
I have managed tonight to test against the constellation at work, and I can reliably reproduce this.
Im not sure how quick of a fix this will be, as it has revealed a few issues in this version of the connection library that only become a problem with such a complex atem.

I shall do my best to get a fix for this asap, as it has a few severe levels to the bug. Ill update you when I have something.

This shouldn't be affected by firmware version, I have been testing against 8.0.2, and is a problem with this model

**Comment by Julusian** [comment]
This should be better in the latest beta build

**Comment by wicherdt** [comment]
latest beta build:
03. 12:55:44 instance(bmd-atem): Configured instance bmd-atem could not be loaded, unknown module
03. 12:55:44 instance(bmd-atem): Configured instance bmd-atem could not be loaded, unknown module
03. 12:55:39 module(bmd-atem): Error loading module: Error: Cannot find module 'C:\Program Files\Companion20-fix\resources\app.asar/lib/module/bmd-atem/dist/index.js'

**Comment by Julusian** [comment]
Huh.. Ill have a look later today

**Comment by Julusian** [comment]
This should be working in the latest build

**Comment by wicherdt** [comment]
OK. Thank you.
