### ISSUE TITLE
ATEM Mini Pro: missing Multiview option on Aux 1 (HDMI out)

### ISSUE THREAD

**Issue by Pekyyyyy** [bitfocus/companion-module-bmd-atem#65]
Set AUX Bus action is missing a dropdown option in Input for a MVW/Multiview. Likely because other ATEMs cannot display Multiviews on Auxes, but ATEM Mini can.

**Comment by Julusian** [comment]
Duplicate of #61 
I will get this done soon, hopefully I can tonight
