### ISSUE TITLE
ATEM Instance Feedback

### ISSUE THREAD

**Issue by Jonhug82** [bitfocus/companion-module-bmd-atem#68]
Hi, I use the ATEM instance and its brilliant. Is it possible to add either a Page Change or Button Press based on ATEM feedback ? 
I have 3 PTZ cameras controlled by 3 x Visca instances and have created 3 pages of preset recalls, 1 per camera. I would like the Preview Bus of an ATEM mixer to switch the page so that the preset recalls are always available for the camera that is on preview
Thanks Jonathan

**Comment by krocheck** [comment]
@Jonhug82, unfortunately there isn't an "automation" structure to hook feedbacks and trigger actions.  I know there's a standing ticket in the main Companion repo for this feature, so I'm going to close this out for now.  Thanks for the feedback!
