### ISSUE TITLE
Downstream key input set broken

### ISSUE THREAD

**Issue by showcom** [bitfocus/companion-module-bmd-atem#70]
Companion 2.1.0 does not change the Downstream Key input or fill. It used to in the previous version.

**Comment by Julusian** [comment]
This is a quick fix, but is blocked behind some other updates to the module that need to be tested before it can be merged in

**Comment by showcom** [comment]
Thanks, ETA?

Lars
501-952-2951
www.larsdesigns.com

**Comment by Julusian** [comment]
Fixed in the latest beta build
