### ISSUE TITLE
Autotrans Failure ProductionStudio4K 

### ISSUE THREAD

**Issue by Noud55** [bitfocus/companion-module-bmd-atem#76]
The Autotrans command is not working correctly both with M/E and DSK on our ATEM ProductionStudio4K (softver 8.21).
when executed the autotrans moves a bit (10%) and stops then...........
With the ATEM MiniPro  these both functions are working perfect with the same control PC, and on StreamdeckXL as well.....
I have noticed that when choosing the ATEM ProductionStudio4K as a device I get some error notifications in the log.....,
choosing the ATEM MiniPro does not give any error notification???

**Comment by Julusian** [comment]
Are you running a build between companion-2.1.1-5c01252-2529 and companion-2.1.1-e442c8c-2555?
The mix stopping sounds like a confirmed (and now fixed) bug in companion between those versions.

I do not understand how it will behave differently on the different models with everything else being the same, the module does not do anything different based on the model for these actions.

What is the error?

**Comment by Noud55** [comment]
Currently runnig on build 2.1.0-47823d0-2493, will update to latest and see if problem is solved.
I found out that when starting the session it works fine and after a while the state of the ATEM PS4K instance status changes from "OK" green to "offline" red........ , 
The error in the log says: "instance(ATEM_PS4k): Number too big: 95>3 (see screenprint)
![screen01](https://user-images.githubusercontent.com/46244406/92389383-45751980-f119-11ea-856e-412dbd3f0cc2.png)

**Comment by Noud55** [comment]
Running on the latest build the issue seems to be solved......., also no error messages in log anymore
