### ISSUE TITLE
ATEM Mini Pro ISO - can't connect

### ISSUE THREAD

**Issue by jeff-vashon** [bitfocus/companion-module-bmd-atem#77]
I can connect to Companion with my ATEM Mini Pro, but I'm not able to connect with my ATEM Mini Pro ISO; both are running ATEM Software Control vers. 8.4.  I presume this is because there is a need for a software update to accommodate the new Pro ISO.  If not, is there something else amiss?

**Comment by Julusian** [comment]
If the mini pro is working with the exact same version of companion and atem firmware, then the mini pro iso will also work.
What version of companion are you running? Perhaps try one of the latest beta builds, as there have been quite a few atem changes since 2.1 was released

**Comment by Julusian** [comment]
@jeff-vashon do you have any more info here? I don't have enough to act on currently

**Comment by Degeert** [comment]
I have the same problem. It works if i select an atem mini but then  i dont get the ISO features. Atem mini ISO is not in the selection list and If i select autoselect, it won't recognise the iso. Where can i find the beta build?

**Comment by Julusian** [comment]
Beta builds are under the 'BUILDS' link at the bottom of 
![image](https://user-images.githubusercontent.com/1327476/94310867-393ee800-ff72-11ea-8703-ed9d30a2a056.png)

If you are running 2.1.0, your best option is to select the mini-pro instead as that is closer in features. But the best option is to update to a beta build as that will recognise it as a mini pro iso, and there is some new functionality for both models in the betas

**Comment by jeff-vashon** [comment]
Thank you Julian!  I really appreciate what you've done to make the stream deck functional for the ATEM.  I've only recently been introduced to the Github universe due to the stream deck and the ATEM (livestreaming is a new world for me).  Is there a way to make a financial contribution that goes directly to you?

 

Thanks

 

jeff

**Comment by Degeert** [comment]
Thanks Juluisian.
Did not noticed the "builds" button.
I will give the beta a try now.

**Comment by Degeert** [comment]
Tested in the beta and it works fine!
Thanks a lot.

**Comment by Julusian** [comment]
@jeff-vashon Thanks for the offer, but I would prefer you gave to the companion project as a whole instead https://opencollective.com/companion

@Degeert thats great to hear :)

**Comment by jeff-vashon** [comment]
Shall do.  Thank you all for what you do!

 

ciao

 

jeff

**Comment by philmoranffab** [comment]
Hi, I have had exactly the same problem.  My ATEM mini pro is recognised, but my new ISO is not.
Working with a Macbook pro with macOS Catalina 10.15.6.  ATEM software controller is version 8.2.3
<img width="384" alt="Screenshot 2020-10-07 at 12 43 53" src="https://user-images.githubusercontent.com/72499015/95321381-483f6780-089b-11eb-9532-cf64adff8a6e.png">

Strange thing is that it see the ISO on the network, but when I click it to select it doesn't connect and goes to the same page.
I'm not experienced in programming and I can't follow much of the above details in this thread.
Can anyone help?
Phil Moran

**Comment by Julusian** [comment]
@philmoranffab it sounds like your atem has an ip that is not accessible from the ip of your machine.
