### ISSUE TITLE
ATEM Mini Pro ISO

### ISSUE THREAD

**Issue by SIGNPAGE** [bitfocus/companion-module-bmd-atem#78]
ATEM Mini and ATEM Mini Pro is supported and works fine with the Steam Deck.
The new model from BMD the ATEM Mini Pro ISO is not supported.
Is this in progress ?

**Comment by Julusian** [comment]
Just tell companion that it is a mini pro.
Everything will work the same.

Ot you could use a beta builds of companion as they recognise and support it.
