### ISSUE TITLE
[BUG] ATEM Control not working correctly

### ISSUE THREAD

**Issue by jameshardy01** [bitfocus/companion-module-bmd-atem#80]
I think that it has something to do with companion not controlling the ATEM. I am on Companion
2.1.0 (47823d0-2493).  It shows this error eventually in the log. The socket process unexpectedly closed (code: "null", signal: "SIGABRT") Any ideas what to try? I have restarted the computer, companion, and the atem. Swapped the ip address. I get it to work for a second, then it does not work.

**Comment by Julusian** [comment]
Try updating to a beta build of companion. It will either resolve your issue or give a more helpful error to work from.
There have been some large changes in the atem module since 2.1.0 that likely fix this problem

**Comment by jameshardy01** [comment]
Ok. I’ll just deal until the next stable comes out, when do you think that will release?

James Hardy
Technical Media Director | Community of Faith
t: (937) 583-5205
e: james@cofchurches.com
400 N. Commerce St.
Lewisburg, OH 45338
________________________________

**Comment by McHauge** [comment]
best gues for a new release would be in Q1 2021, would be my gues.

**Comment by Julusian** [comment]
2.1.2 has been released, which I believe will resolve this
