### ISSUE TITLE
Change USK key type

### ISSUE THREAD

**Issue by X21de** [bitfocus/companion-module-bmd-atem#82]
A) I have the ATEM Television Studio HD and the ATEM Mini Pro and on both I can't change the 
     Inputs for the Down-Stream-Keyer.
     For the Upstream-Keyer it works - on both devices.

B) Talking over the Upstream-Keyer, it would be very helpful if I could change the Keyer Funktion
(Luma, Chroma, Pattern, DVE)
For some Cases I have to change between the 
Host-Camera 'Chroma-Keyer' and a PiP for the Presenter and the PowerPoint.
As a workaround I run first a Macro on the switcher to switch between the two.
I see if you implement Point B, wishes to change the PiP Size and Position will follow ;)

ATEM MiniPro 8.4, ATEM TSHD 8.1.1, Companion 2.1.0

**Comment by NerdsLTD** [comment]
+1 for that! I ended up doing it with macros.

**Comment by Julusian** [comment]
A) This is a known issue in 2.1.0 and is fixed in the 2.1.1 beta builds.

B) Yeah, this is not implemented yet

**Comment by Julusian** [comment]
This is implemented and will be in the betas shortly
