### ISSUE TITLE
ATMI Mini Connecting Status Loop

### ISSUE THREAD

**Issue by Jerhym** [bitfocus/companion-module-bmd-atem#84]
Hello,

I am having an issue connecting my new ATEM Mini to Companion - In the Connections and Instances Page my status is Listed as **_Connecting_** nonmatter the changes I have made to both the software and hardware connections.

I started with the current version of ATEM Control 8.4 and Companion 2.1.0 - ATEM and Computer Connected to the same router via Ethernet. IP Addresses in both cases correct - Status Connecting

**- Next Attempt -**

ATEM Control 8.4 and Companion 2.1.0 - ATEM connected straight to Computer - Ethernet. IP Addresses in both cases correct - Status Connecting (UNCHANGED)

**- Next Attempt -** ( Downloaded ATEM 8.1)

ATEM Control 8.1 and Companion 2.1.0 - ATEM and Computer Connected to the same router via Ethernet. IP Addresses in both cases correct - Status Connecting (UNCHANGED)

**- Next Attempt -** 

ATEM Control 8.1 and Companion 2.1.0 - ATEM connected straight to Computer - Ethernet. IP Addresses in both cases correct - Status Connecting (UNCHANGED)

**- Next Attempt -** ( Downloaded Companion Beta - 2.1.1 (6ba2e29-2601) )

ATEM Control 8.1 and Companion Beta - 2.1.1 (6ba2e29-2601) - ATEM and Computer Connected to the same router via Ethernet. IP Addresses in both cases correct - Status Connecting (UNCHANGED)

**- Next Attempt -**

ATEM Control 8.1 and Companion Beta - 2.1.1 (6ba2e29-2601) - ATEM connected straight to Computer - Ethernet. IP Addresses in both cases correct - Status Connecting (UNCHANGED)

**- Next Attempt -** (Downloaded ATEM 8.5)

ATEM Control 8.5 and Companion Beta - 2.1.1 (6ba2e29-2601) - ATEM and Computer Connected to the same router via Ethernet. IP Addresses in both cases correct - Status Connecting (UNCHANGED)

-

One last quick modifier here - (Every attempt I also changed the Model From: Auto Detect -> Mini -> Mini Pro -> Mini Pro ISO.)  No change to the status on any of those modifiers.

- 

That is what I have tried so far, I may be missing something really easy to spot, but I would love a push in the right direction!

Let me know what else I should be trying!

Thanks!

J

**Comment by haakonnessjoen** [comment]
Are you able to connect to the Atem using the atem software on the same computer? Without being connected via usb to the atem mini?

**Comment by Jerhym** [comment]
No, without the USBC the ATEM is not connecting. 

Attached to the computer directly or through a switcher or directly into the router, it can not connect to the ATEM Control Software with out being connected to USBC. 

I copied the IP address when it was connected to USBC, still no go.

So I suppose I need to figure that issue out - any advice?

Thanks

**Comment by Jerhym** [comment]
After Reassigning the IP a few times and changing cables - All seem to be working!

Thank you for the mental nudge in the right direction!

J
