### ISSUE TITLE
Take Upstream Key Off Air

### ISSUE THREAD

**Issue by RobbieBott** [bitfocus/companion-module-bmd-atem#86]
Hello,

I'm not sure where to get support at so I figured I would ask here. 
If I use the command on key down "Set Upstream KEY OnAir" I cannot figure out how to take it off air.

Can anyone help with that?

**Comment by MarauderSeeker** [comment]
You use the same action and just change the option (onAir) to “Off” instead of “On Air”.

**Comment by RobbieBott** [comment]
> You use the same action and just change the option (onAir) to “Off” instead of “On Air”.

Any way to fade that in and out?

**Comment by MarauderSeeker** [comment]
What I do is set it on preview and then use the AUTO transition for the fade

**Comment by RobbieBott** [comment]
> What I do is set it on preview and then use the AUTO transition for the fade

I really do appreciate the help!! 

When I choose the option to set a input on preview that list consists of:
Inputs 1-8
Color Bars
Color 1
Color 2
Media Player 1
Media Player 1 Key
Media Player 2
Media Player 2 Key

So the correct input source, is Input 1 which for me is Presenter.

I am setting that as the input on preview and then choosing the option to auto transition. The outcome is simply changing that input onto program and moving the program input to preview. It's not putting that source into key. 

Am I using the wrong options?

**Comment by MarauderSeeker** [comment]
I have a macro setup that sets the key on preview

**Comment by Julusian** [comment]
You will need to use the "Change transition selection" action, to set the next transition to apply to the key, then run the auto transition, and then possibly another "Change transition selection" action to change it back to the default of background (the input source).

This isnt something we can really simplify as it is a few separate atem commands that rely on the atem not being in the middle of a transition already.
