### ISSUE TITLE
Add variables for USK and DSK State

### ISSUE THREAD

**Issue by dseehof** [bitfocus/companion-module-bmd-atem#87]
Is it possible to add variables for the state of the USKs and DSKs of the switchers? I'm testing the new scheduling and trigger functionality mentioned [here](https://github.com/bitfocus/companion/pull/1186) and this would allow me to do quite useful automations.

**Comment by kellertobias** [comment]
having the same issue, I want to automate a clients workflow with logos in title cards, which the decrease in size to become a bug in the corner. At the moment I am doing this with BMs macros, however programming the macros is pain in the ass in BMs software...

**Comment by Julusian** [comment]
The triggers system can now use feedbacks, so this should no longer be necessary to add variables
