### ISSUE TITLE
Supersouce 2 not available

### ISSUE THREAD

**Issue by matt-hand** [bitfocus/companion-module-bmd-atem#88]
When looking at the configurations SS2 is listed as SS1 and does not appear any other way to be able to program. This is for Constellation in 4k/HD mode.

**Comment by matt-hand** [comment]
Hello! Just wanted to check back in and see what the status may be on this. Thanks in advance.

**Comment by Julusian** [comment]
This is fixed in the `2.2.0-77ba794-2756` beta build

**Comment by matt-hand** [comment]
Fantastic! Will wait for the new build to be published and will test it out. Thanks for all of the great work.
