### ISSUE TITLE
no connection with atem mini on version 8.5

### ISSUE THREAD

**Issue by Joe-Bio** [bitfocus/companion-module-bmd-atem#89]
I know that support for atem switches (in this case atem mini pro iso) is until firmware version 8.1, however read this after installing 8.5. With this version, connection is not possible. Problem: downgrading the atem to firmware 8.1 is also not possible. Any idea when 8.5 will be supported by companion? :)
BTW: Thanks a lot for this cool piece of software...

**Comment by McHauge** [comment]
And you are using it via RJ45 and not usb right?

**Comment by Joe-Bio** [comment]
Yes. The ip should work, ping works. It get stuck at connecting (yellow)

Von meinem Huawei-Telefon gesendet


-------- Ursprüngliche Nachricht --------
Von: Andreas Thomsen <notifications@github.com>
Datum: So., 25. Okt. 2020, 17:44
An: bitfocus/companion-module-bmd-atem <companion-module-bmd-atem@noreply.github.com>
Cc: "Fensterle, Joachim" <Joachim.Fensterle@hochschule-rhein-waal.de>, Author <author@noreply.github.com>
Betreff: Re: [bitfocus/companion-module-bmd-atem] no connection with atem mini on version 8.5 (#89)

And you are using it via RJ45 and not usb right?

**Comment by McHauge** [comment]
Huh

**Comment by Julusian** [comment]
Could you try using a recent 2.1.1 beta build of companion?
8.5 should work fine with both (I use it myself with the betas), but it may not

**Comment by Joe-Bio** [comment]
Julian,

works now! Thanks a lot. Still using 2.1.0, was my fault – although checking twice the ip address I had a typo ☹. Sorry for this.

Will go to the donation tomorrow ☺

Great peace of software – congrats.

Best,

Joe

Prof. Dr. Joachim Fensterle
Biotechnologie / Bioengineering

[Beschreibung: Beschreibung: HSRW-Logo_NEU kleiner Rahmen.jpg]

Hochschule Rhein-Waal
Marie-Curie-Str.1
(Navigationsadresse: Wiesenstraße 35)
D-47533 Kleve

Tel.: +49 2821 806 73 219
Fax: +49 2821 806 73 44219

Email: joachim.fensterle@hochschule-rhein-waal.de<mailto:joachim.fensterle@hochschule-rhein-waal.de>
Internet: www.hochschule-rhein-waal.de<http://www.hochschule-rhein-waal.de/>

Von: Julian Waller [mailto:notifications@github.com]
Gesendet: Sonntag, 25. Oktober 2020 17:49
An: bitfocus/companion-module-bmd-atem <companion-module-bmd-atem@noreply.github.com>
Cc: Fensterle, Joachim <Joachim.Fensterle@hochschule-rhein-waal.de>; Author <author@noreply.github.com>
Betreff: Re: [bitfocus/companion-module-bmd-atem] no connection with atem mini on version 8.5 (#89)


Could you try using a recent 2.1.1 beta build of companion?
8.5 should work fine with both (I use it myself with the betas), but it may not

**Comment by Joe-Bio** [comment]
Just for the sake of completion, at present just complains “Unknown model: ATEM Mini Pro ISO. Some bits may be missing”.

If I identify a “missing bit”, I keep you updated ☺

Prof. Dr. Joachim Fensterle
Biotechnologie / Bioengineering

[Beschreibung: Beschreibung: HSRW-Logo_NEU kleiner Rahmen.jpg]

Hochschule Rhein-Waal
Marie-Curie-Str.1
(Navigationsadresse: Wiesenstraße 35)
D-47533 Kleve

Tel.: +49 2821 806 73 219
Fax: +49 2821 806 73 44219

Email: joachim.fensterle@hochschule-rhein-waal.de<mailto:joachim.fensterle@hochschule-rhein-waal.de>
Internet: www.hochschule-rhein-waal.de<http://www.hochschule-rhein-waal.de/>

Von: Julian Waller [mailto:notifications@github.com]
Gesendet: Sonntag, 25. Oktober 2020 17:49
An: bitfocus/companion-module-bmd-atem <companion-module-bmd-atem@noreply.github.com>
Cc: Fensterle, Joachim <Joachim.Fensterle@hochschule-rhein-waal.de>; Author <author@noreply.github.com>
Betreff: Re: [bitfocus/companion-module-bmd-atem] no connection with atem mini on version 8.5 (#89)


Could you try using a recent 2.1.1 beta build of companion?
8.5 should work fine with both (I use it myself with the betas), but it may not

**Comment by Julusian** [comment]
@Joe-Bio Thats great to hear.

'Some bits may be missing' is a bit of a misleading warning. Many features are 'missing' (unimplemented) for every model, that simply refers to that some inputs or something may be missing in some places as we can't always predict what should be offered from the data we get from the atem. 
From memory for a mini pro iso, I think its just the multiview missing form the aux, and that should be it.
