### ISSUE TITLE
audio input fade

### ISSUE THREAD

**Issue by kellertobias** [bitfocus/companion-module-bmd-atem#92]
I want to automate the workflow for a client.
They are using an Atem Mini Pro for their Youtube streams and have a fixed workflow.
At the beginning, we show a title card, then the narrators mic fades in, music is getting lower in volume, and we do the transition. a few moments later we fade music completely off.
At the end, the procedure is reversed.

I cannot find a way to do fades and/or set sound volume at all in the companion app.

**Comment by Mackenflow** [comment]
Yes, some audio control would be great.

**Comment by Julusian** [comment]
Audio control is in the 2.1.1 beta builds of companion.
There is no support for doing fades yet

**Comment by Mackenflow** [comment]
What about an option for a relative boost on the fader, instead of setting a specific level?
+1dB on Mic 1, e.g.

**Comment by Julusian** [comment]
This is done in the `2.2.0-77ba794-2756` build
