### ISSUE TITLE
Camera Control 

### ISSUE THREAD

**Issue by Riot-StefanSchindler** [bitfocus/companion-module-bmd-atem#94]
Hi, 

we´re using BMD ATEMS with BMD Cameras  - the camera control works via Atem and its received via the sdi in on the camera. we are currently using a skaarhoj rcp v2 to control the camera. 

what i am looking for here is a way to trigger the button "autofocus " + some of the other features there ( mainly need focus) 

having also some volume control over the audio mixer would be great

**Comment by Julusian** [comment]
It is possible to control some audio levels in the 2.1.1 betas.

Camera control is not implemented, and is quite a large task so unlikely to happen soon

**Comment by BibraDesign** [comment]
Just wanted to +1 on this, would be very keen on having camera control implemented in Companion. I’d love to be able to set a button to trigger a certain gain value or whitebalance value as well as open / close the IRIS in small steps.
If there would be an option to first select a camera as a variable and the have the other actions use that camera number as a variable would be great. Is there a chance this is going to get implemented?

**Comment by zebracookie** [comment]
You can use the Middle Control  Companion plugin. It does exactly that, you can control all the Blackmagic camera related settings https://www.middlethings.co/documentation/docs/Usage/bitfocus-companion/

**Comment by Cows2Computers** [comment]
With the new Stream Deck+ having rotary knobs it would awesome to do camera control. I would be willing to contribute to a bounty on this.

**Comment by clboles** [comment]
@Julusian, does the addition of CameraControlCommand in atem-connection (thanks for that contribution!) unblock enabling basic camera control in this plugin?  Camera control is the last piece that requires me to keep ATEM Software Control open in addition to Companion.  Thanks!

**Comment by Julusian** [comment]
Maybe. Ideally more should be added to atem-connection to help with the intepreting and generating of the CameraControlCommand, so far it is the bare minimum needed to allow someone to do all that logic themselves.

The main problem is that the values used by that command are not really documented. Not even in the official SDK. I suspect that the values documented in https://documents.blackmagicdesign.com/UserManuals/ShieldForArduinoManual.pdf?_v=1581580811000 will be what we should use, but that disagrees with a PR that someone opened for atem-connection, so I don't know which to trust.

I don't have a blackmagic camera to test with, so this is very hard for me to motivate looking at doing myself.
I did do an implementation in another library once, but getting tests to work reliably when using newer ATEM firmware was a pain, a few times they broke with no clear way to know which to expect. Thats a challenge when wanting a stable api and to support as many atem firmware versions as we do.

**Comment by GarthDB** [comment]
Sep 2023, Blackmagic released API (local REST) documentation for controlling cameras directly. https://documents.blackmagicdesign.com/DeveloperManuals/BlackmagicCameraControl.pdf

This could be separate from the ATEM module, but this module would still be helpful for controlling cameras outside of the supported list or HDMI/SDI controlled devices through the ATEM.

This is mentioned in this request: https://github.com/bitfocus/companion-module-requests/issues/719

**Comment by GarthDB** [comment]
Another use case for the Blackmagic Camera Control would be to control one of the supported cameras connected to the network with an ethernet adapter. The [documentation](https://documents.blackmagicdesign.com/UserManuals/BlackmagicMicroStudioCamera4KG2Manual.pdf?_v=1701331211000) for the camera suggests you can control it directly over the network without an ATEM.

> The following Blackmagic cameras are compatible with Camera Control REST API: 
> * Blackmagic Cinema Camera 6K
> * Blackmagic Micro Studio Camera 4K G2
> * Blackmagic Studio Camera 4K Plus
> * Blackmagic Studio Camera 4K Pro
> * Blackmagic Studio Camera 4K Pro G2
> * Blackmagic Studio Camera 4K Plus G2
> * Blackmagic Studio Camera 6K Pro

> ## Downloading API’s from your Camera
> You can download REST API YAML documentation from your camera by adding /control/documentation.html to the end of the camera’s Web media manager URL or IP address. For example, https://micro-studio-camera-4k-g2.local/control/documentation.html

**Comment by Julusian** [comment]
@GarthDB lets keep this issue about doing camera control via the atem.
While REST is an option for some cameras, that would be implemented as a new module. I've created https://github.com/bitfocus/companion-module-requests/issues/1383 as a replacement for https://github.com/bitfocus/companion-module-requests/issues/719 to describe the REST api and a potential new module.

**Comment by Julusian** [comment]
A first pass of this is done and will be in the betas shortly.

If anything doesn't work or you think is missing, please open new issues

**Comment by videojim123** [comment]
I would like to test the beta for BMD camera control discussed in this thread.
I'm not that familar with Github, so I'm not sure how to accomplish getting the beta module.
Thanks,
