### ISSUE TITLE
Blackmagic Atem Module not available in Beta 2.1.1

### ISSUE THREAD

**Issue by manuspam** [bitfocus/companion-module-bmd-atem#95]
Hi all, 
It seems that the Blackmagic Atem Module is just missing in the new Beta 2.1.1
https://share.getcloudapp.com/JruqAlLb
I cannot find it in the dropdown list, and it seems to be missing in the app itself, see warning.
Am I missing something here?

**Comment by Julusian** [comment]
Use a newer build. That one is 4 months old, and the atem module missing is a known issue of that one build.
