### ISSUE TITLE
[BUG] ATEM TV Studio 4K no longer recognised / functioning

### ISSUE THREAD

**Issue by JamSponge** [bitfocus/companion-module-bmd-atem#97]
![image(1)](https://user-images.githubusercontent.com/13683962/102013255-cf4f0700-3d46-11eb-9806-c16998a9e805.png)

**Comment by OliverSchlutz** [comment]
Same probs

**Comment by Julusian** [comment]
This is fixed in the `2.2.0-77ba794-2756` beta build
