### ISSUE TITLE
ATEM program image as LIVE button.

### ISSUE THREAD

**Issue by fkmobile** [bitfocus/companion-module-bmd-atem#98]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
Can we get jpeg images from the ATEM program on a button.  Ecamm live and other software apps allow images to show up on the streamdeck which can help.

**Is this platform dependent (windows, mac, ..)?**
Any platform

**If documentation is required to implement, do you know where to find it?**
https://youtu.be/Ts-o64Tdo1k?t=1061

**Usecases**
1) times you do not have a monitor
2) When you place just a stream deck in a location for quick actions without a monitor

**Comment by Julusian** [comment]
I think the simple answer here is this is no

Firstly, in the video you linked that is done via the elgato software which will likely be using an api in Ecamm to stream the images, and can be done within the machine.

I can think of a couple of ways to do this with some atems:
1) The mini range allow the atem to take a snapshot to the media pool, which we could trigger and transfer off. This will be horribly inefficient, and in a best case scenario could do about 1 frame a second (limited by the network on the atem), and be about a second delayed. It is also likely to get confused, and depending on how the atem feature works, risks wiping other stills in the pool. or could have other side effects
2) Some older models can be connected over usb to capture video. This could work, but requires them to be connected via usb, and is something in my experience that doesnt work well/at all with recent firmwares and will likely take exclusive control of the 'camera' device

A better way for this would be to capture the program output via some pcie/usb capture card, and for a more generic flow of streaming video into a button. But I dont think companion has a great structure for this to be done currently. It could be looked at if there is demand
